### ISSUE TITLE
BT control nodes versus XML equivalents

### ISSUE THREAD

**Issue by mjeronimo** [BehaviorTree/BehaviorTree.CPP#105]
@facontidavide I'd like to get your input on this issue that we're discussing in nav2:

https://github.com/ros-planning/navigation2/issues/888

**Comment by facontidavide** [comment]
Sent the feedback already. I am closing this issue.

For the records, I believe that anyone should feel free to create not only their custom Action and Condition nodes, but also the Control and Decorator nodes that make their BT simpler and more expressive.

I don't believe that sticking with the one I provide is being a purist, nor that it is best practice.

Making your BT easy to read is best practice. If a CustomNode achieve that, go on.

Think about it as a Domain Specific Language.
