### ISSUE TITLE
notify_start() should be halt()

### ISSUE THREAD

**Issue by wan053670** [BehaviorTree/BehaviorTree.CPP#109]
action_node.cpp,line 129 , in function stopAndJoinThread（）,  notify_start() should be modified to halt()

**Comment by wan053670** [comment]
oh, I made an mistake, should check the node status first, if the status equals running ,calls halt(), else, just as original code, calls nofitystart() to unlock the wait.

**Comment by facontidavide** [comment]
Thanks for pointing this out. i actually make sense. Fixed
