### ISSUE TITLE
InverterNode is registered as "AlwaysSuccess"

### ISSUE THREAD

**Issue by marcmilks** [BehaviorTree/BehaviorTree.CPP#111]
Same registration id is being used for Always Success and Inverter. Name needs to be replaced.

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/89a1461d4b9da580e68697b67537e2e762f98cb5/src/decorators/inverter_node.cpp#L21

**Comment by facontidavide** [comment]
Wow, thank you for noticing. Fixed
