### ISSUE TITLE
Variable running_count is never read

### ISSUE THREAD

**Issue by marcmilks** [BehaviorTree/BehaviorTree.CPP#112]
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/2db7bfeeb968422acee6083b4b0fb69afbae7fbf/src/controls/reactive_sequence.cpp#L21

Per the Title the variable is created, incremented, but never read and can likely be removed

**Comment by facontidavide** [comment]
yes, that is some orphaned code that I left there for debugging purpose
