### ISSUE TITLE
PublisherZMQ throws std::logic_error

### ISSUE THREAD

**Issue by bhagwanalbert** [BehaviorTree/BehaviorTree.CPP#114]
Hi,

Something similar to issue #38  is happening to me with PublisherZMQ. I have the same code for all the loggers and this one does not work even if it is deleted. Only when the ROS node dies it lets me use this publisher in order to view the new tree in Groot.

Thanks in advance.

**Comment by facontidavide** [comment]
fixed. Thanks for reporting
