### ISSUE TITLE
Groot include directory rename

### ISSUE THREAD

**Issue by bhagwanalbert** [BehaviorTree/BehaviorTree.CPP#128]
Hi,

Just updated the BehaviorTree.CPP library and modified my code to adapt the include directory rename. But, the problem is that Groot has not been updated, so I would be grateful if you could add the "_v3" in the corresponding includes of Groot library.

I have done the modifications in local, but as my colleagues are now using my code they are having troubles to compile Groot due to this problem.

Thanks in advance!

**Comment by facontidavide** [comment]
done
