### ISSUE TITLE
base.h:56:10: fatal error: flatbuffers/stl_emulation.h: File or Directory not Found

### ISSUE THREAD

**Issue by BorgesJVT** [BehaviorTree/BehaviorTree.CPP#134]
The /BehaviorTree.CPP/3rdparty/flatbuffers directory contains the stl_emulation.h file, but in CMakeLists.txt it is actually using /BehaviorTree.CPP/include/behaviortree_cpp_v3/flatbuffers directory, which does not have stl_emulation.h but other files.

**Comment by facontidavide** [comment]
Have a look at the last commit, it should solve the issue.

https://github.com/BehaviorTree/BehaviorTree.CPP/commit/43c003d3fe940e09302458784d498fb9ceaf4494

**Comment by facontidavide** [comment]
I will optimistically close this. Tell me if the problem persists
