### ISSUE TITLE
Crash of CoroActionNode in MACOS

### ISSUE THREAD

**Issue by benmoggee** [BehaviorTree/BehaviorTree.CPP#143]
Hi,

I get this error when using CoroActionNode. I run on MACOS the latest.

 ./t09_async_actions_coroutines
action_A: Started. Send Request to server.
action_A: Waiting Reply...
t09_async_actions_coroutines(2246,0x10c055dc0) malloc: Incorrect checksum for freed object 0x7fa299c03e48: probably modified after being freed.
Corrupt value: 0x7fff6672b093
t09_async_actions_coroutines(2246,0x10c055dc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./t09_async_actions_coroutines

**Comment by facontidavide** [comment]
I know it doesn't help but... it works on my machine :(

I don't know how to reproduce this error

**Comment by facontidavide** [comment]
I refactored the entire CoroAction implementation. 

Now, it will require Boost 1.59+

Note that in most cases you may replace CoroAction with something more straightforward like **StatefulActionNode**

**Comment by benmoggee** [comment]
Thanks. I got it to work by doing what was recommended in this issue. I will look at the new implementation a little later.

![image](https://user-images.githubusercontent.com/18419125/77293474-b0a16f80-6ce2-11ea-89bc-73c87304dcf6.png)
