### ISSUE TITLE
How to reset CoroAction Node to a clean state?

### ISSUE THREAD

**Issue by Jconn** [BehaviorTree/BehaviorTree.CPP#146]
I've been stuck on a crash in the ros2 navigation stack documented here: https://github.com/ros-planning/navigation2/issues/1439

From the ticket:

> Each time we cancel a NavigateToPose goal, we call the behavior tree reset function , which sets the state of every node in the behavior tree to idle.
> 
> The nav2 BtActionNode inherits from BT::CoroActionNode
> 
> Even though we set the CoroActionNode to status idle, that doesn’t reset the state of:
> _p->coro or _p->pending_destroy in that object.
> But those two variable states are only valid on the current thread, because they dictate how the node interacts with: thread_local static Ordinator ordinator;
> 
> Because of the thread_local specifier, every thread has a unique ordinator object.
> 
> The next time we set a NavigateToPose goal, a different thread is spawned to handle the request. That thread starts running the behavior tree object that had its NavigateToPose request cancelled.
> 
> This is how the CoroActionNode gets in a bad state, because _p->coro and _p->pending_destroy have not been reset, but this new thread has a new ordinator

So my question is: is there any way to reset a CoroAction Node to a clean state?

**Comment by facontidavide** [comment]
The answer is not what you may expect...

Do not use CoroAction!

My sad story is that I nerited the **AsyncAction** from version 1.X. I finally realized that it is almost impossible for me to avoid race conditions and to correctly instruct people how to implement this to make it really asynchronous.

I tried to solve this problem with the coroutines. This solved the problem of race conditions, but, as you noticed, it is still unclear how to correctly clean up your state.

Nowadays (I need to reflect this in the documentation, I think the best model is **StatefulAction** 

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/action_node.h#L158

Where it is much cleaner how to implement an asynchronous node with a cleanup.

I need to dif into this to see if I can find a solution.

**Comment by facontidavide** [comment]
Anyway, to close this issue.

I recently made the decision to forbid my used from using setStatus() https://github.com/BehaviorTree/BehaviorTree.CPP/commit/4f30e3a42ff0c657eb5711d7ae94318fde93bd60

The only correct way to "stop" a node is not by setting its state to IDLE (you shouldn't, only the parent node should), by rather calling halt()

**Comment by facontidavide** [comment]
I finally understoof the problem:

> Even though we set the CoroActionNode to status idle, that doesn’t reset the state of:
> _p->coro or _p->pending_destroy in that object.

I have **never** expected multiple threads to  run the` tree.root_node->executeTick()`

In fact`CoroAction` is already robust to the fact that a different thread may calls `halt()`... I forgot that I fixed that in the past!

But it will fail when multiple threads call `executeTick().`

I don't have a "solution". Either:

- don't use CoroAction. looking at the [source code here](https://github.com/ros-planning/navigation2/blob/master/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp), the change should be pretty easy to do.

- be sure that there is only one thread executing the thread. I would love to do some code review with you to understand why you are spawning different threads every time.

**Comment by facontidavide** [comment]
I am happy to say that this problem is solved.

I replace the old coroutine library with boost::coroutine2, that solves the problem

https://github.com/BehaviorTree/BehaviorTree.CPP/commit/02330ac036621f7ad3c169abde88525ff5463463
