### ISSUE TITLE
real-time monitor cannot connect to port

### ISSUE THREAD

**Issue by kevincameronmtl** [BehaviorTree/BehaviorTree.CPP#148]
Hello,
im trying to be able to use the real-time monitor to connect to a custom BT. 
I always get the message that it cannot connect to localhost:1666

i noticed a similar issue, and the suggestion was to use ZMQ

PublisherZMQ publisher_zmq(&mTree);

is there an example that has this?

thanks

**Comment by facontidavide** [comment]
Yes, [tutorial 5 ](https://www.behaviortree.dev/tutorial_05_subtrees/)... just updated.

See file https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t05_crossdoor.cpp
