### ISSUE TITLE
Default input port value

### ISSUE THREAD

**Issue by shivaang12** [BehaviorTree/BehaviorTree.CPP#153]
@facontidavide I am using default value for input ports but couldn't able to make it work. Can you point me to unit test which test this feature? (as you mentioned on #56 about unit test.)

Thanks!

**Comment by leewo0** [comment]
@shivaang12 ”default_value“ of "InputPort" and "OutputPort" is misunderstanding. After i checked the source code, i found the "default_value" is used to set the port remapping value if an inputport's remapping value is missed. And there might be a bug, as the source code in xml_parsing.cpp shows:
`        // use default value if available for empty ports. Only inputs
        for (const auto& port_it: manifest.ports)
        {
            const std::string& port_name =  port_it.first;
            const PortInfo& port_info = port_it.second;

            auto direction = port_info.direction();
            if( direction != PortDirection::INPUT &&
                config.input_ports.count(port_name) == 0 &&
                port_info.defaultValue().empty() == false)
            {
                config.input_ports.insert( { port_name, port_info.defaultValue() } );
            }
        }` 
`direction != PortDirection::INPUT` should be `direction == PortDirection::INPUT`.
Anyway, i also want to find out the way set a default value for a blackboard value. (I have to initialize them within extra nodes.)

**Comment by facontidavide** [comment]
it is most probably a bug. I need to look into this... soonish

**Comment by facontidavide** [comment]
Thanks for insisting ;)

it was indeed a bug. Fixed.

You can find an example here: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/tests/gtest_ports.cpp

**Comment by SteveMacenski** [comment]
@facontidavide when can we expect to see this in a release?

**Comment by facontidavide** [comment]
I am trying to fix as many open issues as possible, including some that may affect Navigation2, to release it.
