### ISSUE TITLE
Create example "Hello World" program

### ISSUE THREAD

**Issue by buddha314** [BehaviorTree/BehaviorTree.CPP#166]
I'm getting several linkage errors, probably due to the fact that a) I'm a weak c++ programmer and b) my `includes` and `CMakelists` is incorrect.  It would be great to have a complete example with examples of both.

**Comment by facontidavide** [comment]
Please create a **CMakeLists.txt** file as described in README

In terms of **cpp** files, you may have a look at the folder **examples**
