### ISSUE TITLE
ROS/ROS2 topic logger

### ISSUE THREAD

**Issue by HansRobo** [BehaviorTree/BehaviorTree.CPP#167]
In navigation2 repository, ros-topic-logger is implemented.
I hope to take in this logger

https://github.com/ros-planning/navigation2/blob/master/nav2_bt_navigator/include/nav2_bt_navigator/ros_topic_logger.hpp

**Comment by facontidavide** [comment]
this will be eventually added here: https://github.com/BehaviorTree/BehaviorTree.ROS

**Comment by SteveMacenski** [comment]
@facontidavide this seems like it should be closed or transferred

**Comment by HansRobo** [comment]
I copied this issue to BehaviorTree.ROS.
So, I close this issue.
