### ISSUE TITLE
Building with c++17

### ISSUE THREAD

**Issue by mechatheo** [BehaviorTree/BehaviorTree.CPP#180]
Hello,

i would like to create a PR which will chage the `CMAKE_CXX_STANDARD` variable to a cached variable, like so:

```CMake
option(BT_CMAKE_CXX_STANDARD "C++ standard used" 14)
set(CMAKE_CXX_STANDARD ${BT_CMAKE_CXX_STANDARD})
```

this allows to change the C++ standard from the command line of by configuring the catkin profile file to contain `-DCMAKE_CXX_STANDARD=17`.

The problem is the following: When we build our projects with c++17 there are linker errors due to incompatible `string_view` implementations. 

Would this be ok? This wouldn't effectively change anything and at the same time allow to use a newer standard more easily.

Please give feedback if this change would be acceptable, then i would prepare a PR.

**Comment by facontidavide** [comment]
I think I solved this, can you check?
