### ISSUE TITLE
Installation Problem with Ros Melodic

### ISSUE THREAD

**Issue by aronadam** [BehaviorTree/BehaviorTree.CPP#186]
Dear,

I experience this error after creating a catkin workspace. I already saw something on modifying the CMakeList.txt file, but the file can not be edited. Maybe I do something wrong?

Kind regards,
Aron

This is the error code:
~/BehaviorTree.CPP/src/bt_factory.cpp:19:10: fatal error: ros/package.h: No such file or directory
 #include <ros/package.h>
              ^~~~~~~~~~~~~~~
compilation terminated.
BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/build.make:182: recipe for target 'BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/src/bt_factory.cpp.o' failed
make[2]: *** [BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/src/bt_factory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:442: recipe for target 'BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/all' failed
make[1]: *** [BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by facontidavide** [comment]
I reverted the last commits, that should fix the issue
