### ISSUE TITLE
Installing  behavior trees with groot to work with ROS

### ISSUE THREAD

**Issue by philip-long** [BehaviorTree/BehaviorTree.CPP#187]
I'm really looking forward to using this library and thanks for making it available!

I've a couple of questions about the installation process. For context I would like to use BTs with ros melodic and Groot. 

1. If I install  using
`sudo apt-get install ros-$ROS_DISTRO-behaviortree-cpp-v3`

Then the example ros repo given https://github.com/BehaviorTree/BehaviorTree.ROS doesn't compile as `tickRoot` doesn't exist.

I assume this means it's an older version. So I can solve this by simply compiling from source and editing the ROS CMakelists so it's looking for find_package(BehaviorTreeV3) instead of behaviortree_cpp_v3 

2. If I install Groot following the instructions I'm also getting some errors
`error: ‘SubtreeNode’ is not a member of ‘BT’ factory.registerNodeType<BT::SubtreeNode>("Root");`

To resolve this I have compiled Groot with catkin and made the following changes similar to those I made with BehaviorTree.ROS, i.e., 

```

if(catkin_FOUND)
find_package(BehaviorTreeV3)
  find_package(catkin REQUIRED COMPONENTS rosbag rosbag_storage roscpp)
.
.
.
target_link_libraries(behavior_tree_editor ${GROOT_DEPENDENCIES} BT::behaviortree_cpp_v3 )
target_link_libraries(Groot behavior_tree_editor BT::behaviortree_cpp_v3)
```
So following the above changes it's Groot is working with ROS etc so just wondering if I've missed something during the process which would of made it a lot easier?

Thanks

**Comment by facontidavide** [comment]
this is an issue of Groot and it has been fixed
