### ISSUE TITLE
Release for Foxy (and probably Noetic, while you're at it)

### ISSUE THREAD

**Issue by SteveMacenski** [BehaviorTree/BehaviorTree.CPP#198]
Per http://repo.ros2.org/status_page/blocked_releases_foxy.html?s=6&r=1 this is shockingly one of the only dependencies missing for navigation2 to be released in ROS2. I expect it to take a while to get released due to the mountain of dependencies (with maintainers that are clearly more on the ball than me).

You may also want to release in noetic while you're at it.

**Comment by facontidavide** [comment]
done

**Comment by SteveMacenski** [comment]
Groovy, thanks Davide!

**Comment by doisyg** [comment]
Yes, thanks! (for Noetic, not using Foxy yet apart for experimenting, @SteveMacenski, you are going to hear a lot from me the day it happens)

**Comment by facontidavide** [comment]
> Groovy, thanks Davide!

@SteveMacenski  do you want me to release for Groovy?   http://wiki.ros.org/groovy :laughing:

**Comment by SteveMacenski** [comment]
No promises Jacob will accept that rosdistro PR 😉
