### ISSUE TITLE
[Question] BT multi process context

### ISSUE THREAD

**Issue by davidtazy** [BehaviorTree/BehaviorTree.CPP#203]
Hi,

In an heavy BehaviorTree context, do you think is it possible to run leaves in another process/cpu ?
how would you achieve this?
If it's a bad idea, can you explain why?

Thx

**Comment by facontidavide** [comment]
not at all. basically this is what everybody does in robotics and the very reason we have AsyncActions.

https://www.behaviortree.dev/bt_basics/

![image](https://user-images.githubusercontent.com/2822888/83891580-b0dfd180-a74d-11ea-908e-32d2866e41d7.png)

What it is often done, is to put in a leave a client code that communicate with inter-process communication with a server that does the real work.
