### ISSUE TITLE
Retaining work on abandoned AsyncActionNodes

### ISSUE THREAD

**Issue by SegfaultCreator** [BehaviorTree/BehaviorTree.CPP#205]
Hello again, 

i got a question about the behavior of the tree, when returning to work on a sequence/reactive sequence, that was previously visited. 

I'm trying to use the behavior tree to protect a position until it is approached by an enemy. The problem is, that when i'm leaving the procedure of flying to the position, the NodeStatus becomes failure, but remains in this state even when the Sequence above is ticked again. But my intention is that the action is repeated when the fallback switches to the right side.

Groot Monitor:
![Task](https://user-images.githubusercontent.com/53517431/84136381-817ddd00-aa4b-11ea-8d1b-5315f54592f4.png)

Is this the desired Treebehavior? I thought that the Node will be ticked again, when the sequence was abandoned before. 

NodeCode(relevant Aspects):
```
BT::NodeStatus FlyToCAP::tick()

halt_requested.store(false);

    while (!halt_requested) {

       ....
        moveAircraftToCap()

        if (GeoHelpers::getGreatCircleDistance(AC, capPos) < 1500 * Meter)
            return BT::NodeStatus::SUCCESS;

        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    return BT::NodeStatus::FAILURE;
}
```

**Comment by facontidavide** [comment]
Assuming his error is obsolete/stale. Closing
