### ISSUE TITLE
How to decode ZMQ message

### ISSUE THREAD

**Issue by ipa-rwu** [BehaviorTree/BehaviorTree.CPP#208]
Hello everyone,

I know we can use Groot to trace behavior tree. But now I want to show it in my web application. I also plan to use ZMQ for communication. I found the code for encoding here.

```    
    SerializedTransition buffer;
    int64_t usec = duration_cast<microseconds>(timestamp).count();
    int64_t t_sec = usec / 1000000;
    int64_t t_usec = usec % 1000000;

    flatbuffers::WriteScalar(&buffer[0], t_sec);
    flatbuffers::WriteScalar(&buffer[4], t_usec);
    flatbuffers::WriteScalar(&buffer[8], UID);

    flatbuffers::WriteScalar(&buffer[10], static_cast<int8_t>(convertToFlatbuffers(prev_status)));
    flatbuffers::WriteScalar(&buffer[11], static_cast<int8_t>(convertToFlatbuffers(status)));
```
Now I am using python to set up a ZMQ subscriber to subscribe. Then I got something like:
```
Received string: [b'\x0c\x00\x00\x00\x01\x00\x01\x02\x00\x01\x03\x00\x00\x04\x00\x00\x02\x00\x00\x00f0\xf2^\xab`\x08\x00\x02\x00\x01\x02f0\xf2^\xfe`\x08\x00\x03\x00\x00\x01'] ...
Received string: [b'\x0c\x00\x00\x00\x01\x00\x01\x02\x00\x02\x03\x00\x01\x04\x00\x00\x02\x00\x00\x00h0\xf2^\xfb`\x08\x00\x03\x00\x01\x02h0\xf2^^a\x08\x00\x04\x00\x00\x01'] ...
Received string: [b'\x0c\x00\x00\x00\x01\x00\x01\x02\x00\x02\x03\x00\x02\x04\x00\x01\x00\x00\x00\x00'] ...
```
Could you guys explain how to decode these messages?
Thank you in advance

**Comment by facontidavide** [comment]
The protocol used is flatbuffer and the schema is here: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/flatbuffers/BT_logger.fbs

For Python, you may have a look to this to generate and use the parser: https://google.github.io/flatbuffers/flatbuffers_guide_use_python.html
