### ISSUE TITLE
Repeat Node (decorator) success condition

### ISSUE THREAD

**Issue by Lakshadeep** [BehaviorTree/BehaviorTree.CPP#217]
From the code here
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/src/decorators/repeat_node.cpp
I understand that `repeat` node stops repeating if the child node fails.

Shouldn't node repeat specified number of times irrespective of success or failure of the child nodes?

**Comment by facontidavide** [comment]
No, that is correct. If you repeat always a certain amount of times, which Status should be returned by the Repeat node?

The last one? Failure if it failed at least once? As you can see, it is tricky.

You may add a **ForceSuccess** decorator to your child, but then I don't know if this is consistent with your semantic.

If you have in mind some other logic that you think it may be useful in some common use case, let me know
