### ISSUE TITLE
Undefined symbol when launching NAV2 of ROS 2 Eloquent

### ISSUE THREAD

**Issue by QQting** [BehaviorTree/BehaviorTree.CPP#221]
Hi @facontidavide 

I saw undefined symbol error when running Navigation2 on ROS 2 Eloquent (Ubuntu 18.04)
```
[bt_navigator-7] [ERROR] []: Original error: Could not load library: /opt/ros/eloquent/lib/libnav2_compute_path_to_pose_action_bt_node.so: undefined symbol: _ZTIN2BT14CoroActionNodeE
bt_navigator_undefined_symbol
```
![bt_undefined_symbol](https://user-images.githubusercontent.com/320113/90652822-1170ac00-e271-11ea-9cf4-58f018052771.png)

I have reported[ this issue](https://github.com/ros-planning/navigation2/issues/1948) to NAV2, but Steve suggests me to tell you that BT.CPP should be included in the next sync.  

Could you help with this?

**Comment by SteveMacenski** [comment]
This isn’t a nav2 or a bt.cpp issue as I tell you in that ticket. This is releases not out as binaries yet.
