### ISSUE TITLE
Typos in tutorial 'Tutorial 5: SubTrees and Loggers'

### ISSUE THREAD

**Issue by jfrascon** [BehaviorTree/BehaviorTree.CPP#222]
The documentation in the 5th tutorial states:

StdCoutLogger logger_cout(tree.rootNode());

Then in the source code for the library we can see:

In the file https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/src/loggers/bt_cout_logger.cpp:
StdCoutLogger::StdCoutLogger(const BT::Tree& tree)

In the file https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/bt_factory.h
TreeNode* rootNode() const;

The documentation should be updated to:
StdCoutLogger logger_cout(tree);
FileLogger logger_file(tree, "bt_trace.fbl");
MinitraceLogger logger_minitrace(tree, "bt_trace.json");

**Comment by facontidavide** [comment]
done. thanks
