### ISSUE TITLE
Pseudocode for Sequences documentation do not agree with source code

### ISSUE THREAD

**Issue by s-trinh** [BehaviorTree/BehaviorTree.CPP#246]
Hi,

I think the pseudocode in this [documentation page](https://www.behaviortree.dev/sequencenode/) are a little bit misleading and in my opinion should be updated with directly reference to the source code.

For instance for `SequenceStar` (the one I am interested in, same for `ReactiveSequence` next children are halted if `RUNNING`) pseudocode is:

```cpp
    status = RUNNING;
    // _index is a private member

    while( index < number_of_children)
    {
        child_status = child[index]->tick();

        if( child_status == SUCCESS ) {
            _index++;
        }
        else if( child_status == RUNNING || 
                 child_status == FAILURE ) 
        {
            // keep same index
            return child_status;
        }
    }
    // all the children returned success. Return SUCCESS too.
    HaltAllChildren();
    _index = 0;
    return SUCCESS;
```

And source code is:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/9b766efbff5857928bef2595257fd18e243000e1/src/controls/sequence_star_node.cpp#L30-L72

If `child_status` is `FAILURE`, it will halt the next children in the source code.

---

If there is a way to directly link to the real source code, it would be better in my opinion. The source code is simple enough to be put directly in the tutorial for me.

**Comment by facontidavide** [comment]
Fixed
