### ISSUE TITLE
HaltAllActions() not halting StatefulActionNodes

### ISSUE THREAD

**Issue by lFatality** [BehaviorTree/BehaviorTree.CPP#249]
Hi there,

I want to stop a tree using `haltAllActions()` (branch `ros2-devel`).
My tree contains `StatefulActionNodes` and they are not halted by the function call.
Looking at the implementation I can see that it only halts `AsyncActionNodes`.

I've added calls to stop the `StatefulActionNodes` and `CoroActionNodes` and then the nodes are halted as expected.
I'm not sure though if this is actually a bug or if I'm understanding the function wrong. Please let me know if this change makes sense. :)

My new `haltAllActions` function:
```
void haltAllActions(TreeNode* root_node)
{
    auto visitor = [](TreeNode* node) {
        if (auto action = dynamic_cast<AsyncActionNode*>(node))
        {
            action->stopAndJoinThread();
        } 
        else if  (auto action = dynamic_cast<StatefulActionNode*>(node))
        {
            action->halt();
        }
#ifndef BT_NO_COROUTINES
        else if (auto action = dynamic_cast<CoroActionNode*>(node))
        {
            action->halt();
        }
#endif
    };

    applyRecursiveVisitor(root_node, visitor);
}
```

**Comment by facontidavide** [comment]
that master is dead. I am removing it.

You should use master
