### ISSUE TITLE
Injecting an object into all nodes

### ISSUE THREAD

**Issue by sjpritchard** [BehaviorTree/BehaviorTree.CPP#252]
Is there a way to inject an object into all nodes at once? The Additional Arguments documentation describes a way to pass arguments on a per-node-type basis, but not (that I can see) to pass an argument for all nodes, regardless of type.

**Comment by facontidavide** [comment]
no, it is not possible

**Comment by ramilmsh** [comment]
> Is there a way to inject an object into all nodes at once? The Additional Arguments documentation describes a way to pass arguments on a per-node-type basis, but not (that I can see) to pass an argument for all nodes, regardless of type.

If all of your nodes are of the same type (say, an ActionNode), you could create a class on top of it, and then inherit your class instead of the ActionNode
