### ISSUE TITLE
Retrieve active node from tree

### ISSUE THREAD

**Issue by dgitz** [BehaviorTree/BehaviorTree.CPP#255]
I have gone through the documentation and don't see a way to get the "active" node from the current running tree.  My use case is mainly for unit testing large trees, that have an ordered structure, and then run through the tree, check each node as necessary (along with other state information that node contains), etc.

My apologies if this is an existing feature.

**Comment by facontidavide** [comment]
no. there isn't such a feature and I am not planning to add it.

It can probably be implemented creating your own "StatusChangeLogger" that inject a callback in any status change.
