### ISSUE TITLE
 Bug in bt ports of type float

### ISSUE THREAD

**Issue by SteveMacenski** [BehaviorTree/BehaviorTree.CPP#256]
Moving ticket from Nav2 on BT.CPP: https://github.com/ros-planning/navigation2/issues/2148

When changing a custom node, the ports aren't working properly it appears from @KvE-sax  report:

`<TemplateCondition port_test_value="0.60"/>`

```
BT::NodeStatus TemplateCondition::tick()
{
  std::lock_guard<std::mutex> lock(mutex_);

  float port_test_value;
  getInput("port_test_value", port_test_value);
  RCLCPP_INFO(node_->get_logger(), 
    "[Template Condition][tick] port_test_value: %f ", port_test_value);
}
  }

static BT::PortsList providedPorts()
  {
    return { 
      BT::InputPort<float>("port_test_value", 1, "Discription of value"),
    };
  }


```

**Comment by facontidavide** [comment]
Fixed. The weird thing is that it should throw, as shown here: 

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/basic_types.h#L68

**Comment by SteveMacenski** [comment]
Thanks!
