### ISSUE TITLE
Support inclusion or aggregation of other XML files

### ISSUE THREAD

**Issue by fafux** [BehaviorTree/BehaviorTree.CPP#259]
HI, I faced a problem in including xml files. I execute bin/t10_include_trees passing as first argument the path to examples/test_files/subtree_test.xml. Below the output:
```bash
terminate called after throwing an instance of 'BT::RuntimeError'
  what():  CheckTemperature is not a registered node, nor a Subtree
Aborted (core dumped)
```
To test I referred to the issue #17

**Comment by asasine** [comment]
The `CheckTemperature` and `SayHello` nodes were not registered with the factory for that example so I went ahead and added them.
