### ISSUE TITLE
printTreeRecursively with custom ostream

### ISSUE THREAD

**Issue by asasine** [BehaviorTree/BehaviorTree.CPP#261]
Is there a way to call `BT::printTreeRecursively(tree.rootNode())` with custom `std::ostream`? It would be useful to use a custom `std::ostream` when a process does not use `std::cout` for logging such as for a ROS node.

**Comment by facontidavide** [comment]
yes, that would be nice....

**Comment by asasine** [comment]
@facontidavide I went ahead and coded up this feature at #264
