### ISSUE TITLE
Recommended way to access xml path?

### ISSUE THREAD

**Issue by juliangaal** [BehaviorTree/BehaviorTree.CPP#270]
I was wondering if you have a suggested way to access the xml file path at runtime, maybe this could be mentioned in the tutorials, as well. I am using a preprocessor macro that is defined with CMake. 

```cmake
target_compile_definitions(behavior_tree PRIVATE BT_XML_PATH="${PROJECT_SOURCE_DIR}/param/behavior_tree.xml")
```
in case you are interested, I'm willing to right something up to add to the tutorials.

**Comment by facontidavide** [comment]
No, there isn't a recommended way. It is a file, just use the same strategy that you would use for any other file.
