### ISSUE TITLE
Add tutorial on Blackboard usage

### ISSUE THREAD

**Issue by sea-bass** [BehaviorTree/BehaviorTree.CPP#278]
It would be very nice to have a tutorial on how to use the Blackboard.

This is mentioned briefly in the ports tutorial with the `SetBlackboard` node, but unless you're setting string values it is very difficult for anyone to infer how they would do this for other data types. Additionally, the non-XML interface (i.e. actually creating a `Blackboard::Ptr` and sharing it correctly, is not documented at all.

I would be happy to help create the tutorial and submit a PR if I can be pointed to some guidance on how to address the above issues.

**Comment by facontidavide** [comment]
Consider that using BlackBoard directly is discouraged. 

People should use ports, whenever they can.
