### ISSUE TITLE
Simple way to get the all node status for the tickRoot()?

### ISSUE THREAD

**Issue by TakaHoribe** [BehaviorTree/BehaviorTree.CPP#284]
Hi! Thank you for the great library.

I'm using the BehaviorTree.CPP in my project, and have a problem.

I'd like to get the node result for the tickRoot(), and I thought I could get the status with this kind of code:
```
  bt_tree_.tickRoot();

  for (const auto & n : bt_tree_.nodes) {
    BT::NodeStatus = n->status();
    ....  // some processing
  }
```

But, since all statuses are set to IDLE at the end of tickRoot (if the return value is SUCCESS or FAILURE), I couldn't get the expected result.

I found that it may be possible to get the status by referring to the code used in the logger, but it will be a bit complicated.

So my question is: Is there any simple way to get the status for the tickRoot()?

For example, I expect like this:

```
  bt_tree_.tickRoot();

  for (const auto & n : bt_tree_.nodes) {
    BT::NodeStatus = n->cashedStatus();  // to get the result for the tickRoot()
    ....  // some processing
  }
```

Any reference implementation is also very helpful.

Thank you!

**Comment by facontidavide** [comment]
Unfortunately, the only solution I can see is to build YOUR own logger:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/loggers/abstract_logger.h

The good news is that it should be trivial. Look at the simplest logger 

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/loggers/bt_cout_logger.h

to see how this works.

Something like:

```c++
class CacheLogger: public StatusChangeLogger
{
public:
     std::map<std::string, NodeStatus> cached_status;
    
     void callback(Duration timestamp, const TreeNode& node,  NodeStatus prev,  NodeStatus status)
    {
          cached_status[ node.name() ] = status;
    }
};
```
