### ISSUE TITLE
Documentation: Reactive squence documentation doesn't match implementation

### ISSUE THREAD

**Issue by matthews-jca** [BehaviorTree/BehaviorTree.CPP#285]
referencing the documentation here regarding the RUNNING of a child node:
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/controls/reactive_sequence.h#L24-L26 

Is actually implemented as "If a child returns RUNNING, the rest of the siblings in the sequence are halted and the node returns RUNNING"
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/src/controls/reactive_sequence.cpp#L30-L39

**Comment by facontidavide** [comment]
fixing this
