### ISSUE TITLE
Documentation and Tutorial Issue with Sequence/Reactive Sequence

### ISSUE THREAD

**Issue by zwgold** [BehaviorTree/BehaviorTree.CPP#291]
Referencing the following:
[`t04_reactive_sequence.cpp`](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t04_reactive_sequence.cpp)
[`tutorial_04_sequence_star.md`](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/docs/tutorial_04_sequence_star.md)

- At the beginning of the `.cpp` file, `Sequence` and `SequenceStar` are referenced, but the ones used are `Sequence` and `ReactiveSequence`.
- I believe the expected outputs are switched, as they are shown in the correct order in the corresponding `.md` file.
- The `.'md` file should be renamed to `tutorial_04_reactive_sequence.md` since `SequenceStar` is not used.

**Comment by facontidavide** [comment]
thanks. Fixing this
