### ISSUE TITLE
RetryUntilSuccessful node typo

### ISSUE THREAD

**Issue by SubaruArai** [BehaviorTree/BehaviorTree.CPP#293]
In `bt_factory.cpp`, line 36:

> ```cpp
>     registerNodeType<RetryNode>("RetryUntilSuccesful");
> ```

`RetryUntilSuccesful` should be `RetryUntilSuccessful`.

There are a few problems that will happen if we just fix this typo:

1. since this is used to parse the xml files, changing this will make certain xml file unusable.
2. `groot` exports `RetryUntilSuccesful`, so we need to fix groot too.

In order to solve this problem, I suggest:

1. add a line `registerNodeType<RetryNode>("RetryUntilSuccessful");` so both versions are usable.
2. make a subclass of `RetryNode` (i.e. `RetryNodeTypo`) and raise warning when used, so that we can depreciate afterwards.
3. fix the import/export of `groot` (I haven't read the code thoroughly, but a quick search indicates that we only need to change 1 line in `bt_editor/resources/NodesStyle.json`, excluding the xml files.)

Fixing is not that hard, but the problem is that there will be some xml files that won't work with groot after the change.
@facontidavide do you have any good ideas?

**Comment by facontidavide** [comment]
Will go for option 1 for the time being, eventually 2
