### ISSUE TITLE
Possibility to sum multiple variables as an input of other Action

### ISSUE THREAD

**Issue by juliamp22** [BehaviorTree/BehaviorTree.CPP#297]
Hello,
I am using the package in noetic version of ROS.
It is possible to sum multiple variables in the same input port of an action node? I have tried it without success.

The error that gives is : _failed because it was unable to find the key [Variable_2]_

Here comes an example:

![Screenshot from 2021-07-22 12-30-08](https://user-images.githubusercontent.com/16271579/126625771-a0597d3a-31a4-44ae-80bc-501bfaaa71ea.png)

Thanks for your time and support,

Júlia

**Comment by facontidavide** [comment]
now possible in version 4, using scripts
