### ISSUE TITLE
Building with colcon for ROS2

### ISSUE THREAD

**Issue by mjeronimo** [BehaviorTree/BehaviorTree.CPP#3]
Can you integrate support for colcon in the CMakeLists.txt? Here's what I have:

https://github.com/mjeronimo/BehaviorTree.CPP/commit/c489ce52dbdf81b5d4c3ffadd9605f49ffd3ab12

**Comment by facontidavide** [comment]
You probably noticed that I carefully created a CMakeLists.txtx file that works both with and without catkin ;)

This means that even the addition of colcon need to be done in a similar way, to be sure that it "automagically" work no matter if you use ROS1, ROS2 or "vanilla cmake".

I will take a look at this

**Comment by mjeronimo** [comment]
Yes, I figured you'd support all of them. Thanks.

**Comment by mjeronimo** [comment]
@facontidavide Any updates on this one? I may be able to take a look at this one if you haven't already.

**Comment by facontidavide** [comment]
Fixed by @mjeronimo  in PR #27
