### ISSUE TITLE
Linking problem with CoroActionNode

### ISSUE THREAD

**Issue by bijoua29** [BehaviorTree/BehaviorTree.CPP#303]
I get the following compiler errors when using a CoroActionNode.

undefined reference to `BT::CoroActionNode::CoroActionNode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BT::NodeConfiguration const&)'
undefined reference to `BT::CoroActionNode::~CoroActionNode()'

I am on Ubunto 20.04 and the latest rolling release of bt

I don't know if this is related to issues #209 or #290 or #299

**Comment by macale-fitech** [comment]
Probably you have build the library without boost packages. 

In the CMakeLists.txt file ( https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/CMakeLists.txt ) there is a smart if statement in lines 21-33 which includes/removes the whole courutine module.

Before building your BehavioralTrees.CPP from source be sure that you have installed `libboost-dev`.
