### ISSUE TITLE
WhileDoElse control node doesn't work with 2 children

### ISSUE THREAD

**Issue by benjinne** [BehaviorTree/BehaviorTree.CPP#338]
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/16763c8169db0c8fa38d1b35d4f460850b9a549a/src/controls/while_do_else_node.cpp#L36

Is thrown with only 2 children present

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/16763c8169db0c8fa38d1b35d4f460850b9a549a/src/controls/while_do_else_node.cpp#L34

Is there something I'm missing?

**Comment by facontidavide** [comment]
I will change this to "WhileDoElse must have 3 children"
