### ISSUE TITLE
documentation link is invalid

### ISSUE THREAD

**Issue by kosuke55** [BehaviorTree/BehaviorTree.CPP#353]
Hi, thank you for the work.
I can't access the documentation link (not only me). [www.behaviortree.dev/](https://www.behaviortree.dev/) 
Please let me know if you have any information.

**Comment by YasarYY** [comment]
Seems like the domain name is expired and entered the grace period.

**Comment by facontidavide** [comment]
Until it is solved, you can use https://behaviortree.github.io/BehaviorTree.CPP/
