### ISSUE TITLE
Dynamically finding a tree node to halt a sub-tree

### ISSUE THREAD

**Issue by mjeronimo** [BehaviorTree/BehaviorTree.CPP#36]
I have a tree like this:

```xml
<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <Sequence name="root">
      <FallbackStar name="check_motion">
        <Inverter name="is_not_stuck">
          <IsStuck/>
        </Inverter>
        <SequenceStar name="stuck_recovery">
          <!-- Needs a halt/cancel of the navigation sub-tree here -->
          <BackUp/>
          <Spin/>
        </SequenceStar>
      </FallbackStar>
      <SequenceStar name="navigate">
        <ComputePathToPose endpoints="${endpoints}" path="${path}"/>
        <FollowPath path="${path}"/>
      </SequenceStar>
    </Sequence>
  </BehaviorTree>
</root>
```

Where there is a condition node to detect if the robot is stuck. At the point that the condition detects the stuck robot, the "navigate" sub-tree is running (FollowPath, in particular). What I'd like to do is: after detecting that the robot is stuck, halt the 'navigate' portion of the sub-tree so that I can execute recovery operations and then continue again with the navigation. I'm thinking of registering an operation ("CancelNavigation", for example) that would dynamically find the "navigate" node to halt it, thereby halting its children. However, I don't see a way to do that. Is that a reasonable thing to consider? Any alternative ways to go about this?

**Comment by facontidavide** [comment]
Interesting question.

In general, if a ControlNode is halted, the running chlidren ar halted too (and this propagates through the subtree.

This should solve your problem. Your original tree is this one, if I loaded it correctly:

![image](https://user-images.githubusercontent.com/2822888/49861157-85e81c00-fdfb-11e8-9bd6-e2635264b54e.png)

I propose this change:

![image](https://user-images.githubusercontent.com/2822888/49861172-8f718400-fdfb-11e8-964a-69fa34dd9593.png)

Let's reason about this second version:

- Branch on the left side, "navigation_subtree". It may fail either because 
       - IsStuck is true
       - ComputePathToPose fails
       - FollowPath fails
- In all of these cases, we execute the branch on the right side, "stuck_recovery", __but___
      - only if IsStuck is true, BackUp and Spin are executed.

Does it make sense.
I would like to write a unit test (hopefully tomorrow) to check that this is actually what happens and be sure that there is not error on my side code-wise.

**Comment by facontidavide** [comment]
By the way, the Fallback("root) can actually be a __FallbackStar__.
In this particular case I am not 100% sure if there would be any noticeable difference in the behavior.

**Comment by facontidavide** [comment]
I have created a unit test that demonstrates that the desired behaviour of my suggestion modification is the expected one:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/gtest/navigation_test.cpp

I hope it helps :)

**Comment by facontidavide** [comment]
WARNINGS: I might have found a bug somewhere else in the code, the logic of the tree is correct but something else might be broken. I am trying to fix this ASAP.

**Comment by orduno** [comment]
I like the proposed change. It's better to have each node clean after itself once they're halted.

I have some questions about how these patterns will scale with more checks and recovery steps for different types of failures, both for the `navigate` branch as a whole but also for the leaf nodes `ComputePathToPose` and `FollowPath`, i.e. we don't necessarily need to report fail on navigation if the branch doing path computation failed given some parameters, perhaps we try something different locally before reporting failure upstream. But that's part of this issue...

**Comment by facontidavide** [comment]
> I have some questions about how these patterns will scale with more checks and recovery steps for different types of failures...

i have questions too ;)
I don't have all the answers, but I am willing to find them.

I will close this issue, since technically it was solved.
Feel free to ask more questions if necessary.

**Comment by facontidavide** [comment]
@orduno and @mjeronimo 

I am currently working on an improvement of the library that might trigger some important changes in the API.
Some open disucssion can be found here: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/output_ports/RoadmapDiscussion.md

I have a quick question for you that might be relevant to find a better solution to this issue.

In your example is "path=${path}" in __ComputePathToPose__ an input or an output?
