### ISSUE TITLE
`FetchContent` only introduced in CMake >= 3.11

### ISSUE THREAD

**Issue by MitchAllain** [BehaviorTree/BehaviorTree.CPP#360]
It seems like the `FetchContent` cmake module was introduced in CMake >= 3.11, however the `CMakeLists.txt` cites version 3.5.1 as the minimum, and notably ubuntu bionic package repositories only provide 3.10.

Introduced in commit 617743b7f931ec10570cb596858f45cd2e9f60cc just prior to 3.6.1 release.

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/e6f241cf31c22db8e91b8376235d1c45cc1b7b25/CMakeLists.txt#L113-L122

**Comment by MitchAllain** [comment]
Not sure if reverting for older CMake versions would be satisfactory for you:
```cmake
elseif(BUILD_UNIT_TESTS)
    if(${CMAKE_VERSION} VERSION_LESS "3.11.0")
      find_package(GTest REQUIRED)
    else()
      include(FetchContent)
      FetchContent_Declare(
        googletest
        URL https://github.com/google/googletest/archive/609281088cfefc76f9d0ce82e1ff6c30cc3591e5.zip
      )
      # For Windows: Prevent overriding the parent project's compiler/linker settings
      set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
      FetchContent_MakeAvailable(googletest)
    endif()
endif()
```

**Comment by facontidavide** [comment]
@MitchAllain thanks, I will implement this solution
