### ISSUE TITLE
CoroActionNode as a ROS Plugin

### ISSUE THREAD

**Issue by dgitz** [BehaviorTree/BehaviorTree.CPP#374]
I am working on trying to use one of my nodes as a stand-alone ROS plugin.  In the ROS plugin documentation, it states "With [pluginlib](http://wiki.ros.org/pluginlib), a constructor without parameters is required for classes so, if any parameters are required, we use the initialize method to initialize the object."  With the CoroActionNode, the only way to pass the name and NodeConfiguration is through the constructor currently.  I understand that the name is not necessarily a problem, but not sure about the impact of just giving a node an empty NodeConfiguration?  In the examples that I've seen I'm not sure that this config is actually used.

**Comment by facontidavide** [comment]
Please use https://github.com/BehaviorTree/BehaviorTree.ROS2
