### ISSUE TITLE
MinitraceLogger throws std::logic_error

### ISSUE THREAD

**Issue by Thordreck** [BehaviorTree/BehaviorTree.CPP#38]
Hi,
I just noticed that the `MinitraceLogger` throws an exception complaining that only one instance is allowed, even if all the previous instances were deleted. I think the reference variable should be set to false in the destructor. From `bt_minitrace_logger.cpp` file (the exception message seems to be a bit off too):

```
MinitraceLogger::MinitraceLogger(TreeNode* root_node, const char* filename_json)
  : StatusChangeLogger(root_node)
{
    bool expected = false;
    if (!ref_count.compare_exchange_strong(expected, true))
    {
        throw std::logic_error("Only one instance of StdCoutLogger shall be created");
    }

    minitrace::mtr_register_sigint_handler();
    minitrace::mtr_init(filename_json);
    this->enableTransitionToIdle(true);
}

MinitraceLogger::~MinitraceLogger()
{
    minitrace::mtr_flush();
    minitrace::mtr_shutdown();
}
```

Cheers.

**Comment by facontidavide** [comment]
you are absolutely right, thanks for reporting. I will fix this ASAP

**Comment by facontidavide** [comment]
i believe it should work now

**Comment by bhagwanalbert** [comment]
Hi,

Something similar is happening to me with PublisherZMQ. I have the same code for all the loggers and this one does not work even if it is deleted. Only when the ROS node dies it lets me use this publisher in order to view the new tree in Groot.

Thanks in advance.
