### ISSUE TITLE
#373 broke existing syntax for subtree inclusion

### ISSUE THREAD

**Issue by sarcasticnature** [BehaviorTree/BehaviorTree.CPP#384]
as mentioned by @asasine in https://github.com/BehaviorTree/BehaviorTree.CPP/pull/358#issuecomment-1126438162, PR #373 broke subtree xml file inclusion if the tree has a `main_tree_to_execute` attribute in the root element.

While this can be solved by removing the `main_tree_to_execute` attribute in the file that has your subtrees to include, this prevents that file from being run on its own.  Being able to run a subtree in isolation is quite useful when you are using BT.CPP at scale, so my view is that the change around this line
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/12373ad8d85286181658ea91720538cb53082083/src/xml_parsing.cpp#L433
in #373 should be reverted so that the `main_tree_to_execute` attribute is only respected in the original file, not included ones.

As an alternative/consequence to reverting the change, in light of the PR's new `bt_factory` functions `registerBehaviorTreeFrom*`, is to change those functions to `registerSubTreeFrom*` so that an arbitrary tree is not selected as the main tree to execute

**Comment by asasine** [comment]
We can't upgrade to the latest version of this library until this is fixed. For what it's worth, my PR contains unit tests that would have caught this, preventing the regression from being checked in.

**Comment by facontidavide** [comment]
ok, will try to fix it this weekend

**Comment by facontidavide** [comment]
Fixed: https://github.com/BehaviorTree/BehaviorTree.CPP/commit/284b1b79c044246051fe55452dee0b365f116714

Thanks for reporting
