### ISSUE TITLE
Reference to the XML Schema in docs is missing

### ISSUE THREAD

**Issue by aroller** [BehaviorTree/BehaviorTree.CPP#391]
See the latest [docs](https://www.behaviortree.dev/xml_format/)

<img width="729" alt="image" src="https://user-images.githubusercontent.com/312949/171477151-3fd200f7-c0b0-433b-8947-ff5dae1d794e.png">

Rendered from [this doc source](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/725eba7e0abbc704284dec393706e5404f1472e3/docs/xml_format.md?plain=1#L129). 

Notice in this [commit](https://github.com/BehaviorTree/BehaviorTree.CPP/commit/4107ac46ef7d9674ca4f84c75c506e6756e0dd96#diff-79ff6d4c4c5088f837c2c924894c74a67948e3440d492898291d70e3c6c56e66), the schema was deleted with no explanation. 

**Acceptance Criteria**

* Was it decided to no longer support an XML Schema?  Then update the docs to remove the reference.
* Was it accidentally deleted?  Recover the schema and the docs work again.

**Comment by facontidavide** [comment]
removed that, because the syntax can't be expressed perfectly as a schema
