### ISSUE TITLE
The Groot is not able to make connection with ROS!

### ISSUE THREAD

**Issue by MortezaAliyari** [BehaviorTree/BehaviorTree.CPP#403]
Hi there
I ran a simple code behavior tree code from this [toturial](https://github.com/sea-bass/turtlebot3_behavior_demos/blob/main/tb3_autonomy/src/autonomy_node.cpp). and I faced this [error](https://drive.google.com/file/d/1OErBtYjPh94oDENxGu_RkmnjAMr2qeTz/view?usp=sharing) after I press the connect button in Groot monitor.
`was not able to connect to "tcp://localhost:1666"`
I also changed the default publisher port and server port numbers to 1664 and 1665 in order.
but nothing changed. 
#### How can I make this connection happen?
I'm using Ubuntu Focal 
CMake 3.2
Ros1 noetic 
####  How can I be sure the `BT::PublisherZMQ publisher_zmq(tree);` this line of my code is publishing something?
Thanks for your support.

**Comment by facontidavide** [comment]
Groot connects to the BT::PublisherZMQ in your behavior tree.
You can include it as shown here: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t05_crossdoor.cpp#L83
