### ISSUE TITLE
SetBlackBoard node is not working

### ISSUE THREAD

**Issue by Zhuoqian0** [BehaviorTree/BehaviorTree.CPP#406]
Hi,
I have a question about this node when I learn to code. The tick() function of set_blackboard_node.h writes setOutput("output_key", value), why not setOutput(key, value)? 
```
    virtual BT::NodeStatus tick() override
    {
        std::string key, value;
        if ( !getInput("output_key", key) )
        {
            throw RuntimeError("missing port [output_key]");
        }
        if ( !getInput("value", value) )
        {
            throw RuntimeError("missing port [value]");
        }
        setOutput("output_key", value);
        return NodeStatus::SUCCESS;
    }
```
Best Wishes！
Thank you!

**Comment by ituren** [comment]
Hi,
I think you should declare your input/output key first to use it.
You can find this declaration in include/behaviortree_cpp_v3/actions/set_blackboard_node.h
`
    static PortsList providedPorts()
    {
        return { InputPort("value", "Value represented as a string. convertFromString must be implemented."),
                 BidirectionalPort("output_key", "Name of the blackboard entry where the value should be written") };
    }
`
Cheers!

**Comment by Zhuoqian0** [comment]
Hi,
Thanks for your suggestion. Adding __shared_blackboard="true" solves the problem.
```
<BehaviorTree ID="MainTree" __shared_blackboard="true">
```
Cheers!
