### ISSUE TITLE
`XMLElement::GetLineNum()` ignores empty lines

### ISSUE THREAD

**Issue by alsora** [BehaviorTree/BehaviorTree.CPP#407]
Hi,

I was trying to parse a BT XML file and I was getting a parsing error.
Trying to debug the error I realized that the line number shown in `src/xml_parsing.cpp` by
```
                ThrowError(node->GetLineNum(),
                           "The node <Control> must have at least 1 child");
``` 

didn't match the actual line number in the file, as it was not counting empty lines.

Is there a way to have `GetLineNum` reflect the presence of empty lines in the XML? This would greatly simplify debugging without having to write XMLs with a lot of Behavior Trees all crammed next to each others.

P.S. I'm running version 3.7.0

**Comment by facontidavide** [comment]
I agree with you, but that is provided by tinyxml2 and I can't do anything about it
