### ISSUE TITLE
Build error with ROS2 humble

### ISSUE THREAD

**Issue by gokul-gokz** [BehaviorTree/BehaviorTree.CPP#411]
I am using default docker image of ROS2 humble.

Installed the behavior tree with the following command:
` sudo apt-get install ros-humble-behaviortree-cpp-v3`

When I build my repository, I get the following error:

> /usr/bin/ld: CMakeFiles/sorting_runtime_app.dir/behavior/behavior_tree_impl.cpp.o: undefined reference to symbol '_ZN3fmt2v86detail18throw_format_errorEPKc'
/usr/bin/ld: /lib/x86_64-linux-gnu/libfmt.so.8: error adding symbols: DSO missing from command line

But I am able to build the repository when I use ROS2 foxy. 

Should I need to change any config to fix in ROS2 humble?

**Comment by facontidavide** [comment]
I just tried compiling with humble and everything seems to work.
If you still have the problem, send me a small project to reproduce it.
