### ISSUE TITLE
Autoremap feature of SubTreePlus does not work for config().blackboard->get()

### ISSUE THREAD

**Issue by mradams-bastian** [BehaviorTree/BehaviorTree.CPP#419]
While I have been able to successfully autoremap blackboard parameters and assign them to subtree input ports from the xml, such as is done in the [unit test example](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/ef68cf1c2e9f30ad63e7e5f5fe4b10fe215db6a2/tests/gtest_subtree.cpp#L174-L203), I have not been able to access the blackboard variables from the code of the node when they are not inputs. For example, suppose that we replicate that same unit test with a modified version of SaySomething that has no input variables, but rather, tries to access the autoremapped variable directly from the blackboard as such:

```
BT::NodeStatus SaySomething::tick()
{
  std::string msg = config().blackboard->get<std::string>("param3");
  std::cout << "Robot says: " << msg << std::endl;
  ...
```

When I try implementing something like this , I get the following runtime error:
```
Blackboard::get() error. Missing key [param3]
```

**Comment by facontidavide** [comment]
It doesn't work because you are strongly discouraged from using the blackboard like that. Only ports should be used
