### ISSUE TITLE
Is it necessary to add a paused state of NodeStatus?

### ISSUE THREAD

**Issue by LuossD** [BehaviorTree/BehaviorTree.CPP#429]
Hi, I'm working on robotic mission systems. Let's Suppose a robot is executing a time-consuming task. It suspends the task after receiving an instruction and resumes the task after receiving another instruction, that is, it executes the task directly.

**Comment by facontidavide** [comment]
You must create an **Asynchronous** action that return RUNNING as long as the action is paused.
