### ISSUE TITLE
Latest version for ROS2 distros

### ISSUE THREAD

**Issue by Excitingship** [BehaviorTree/BehaviorTree.CPP#432]
Hello, I found that the BehaviorCPP version for Galactic and Humble in http://packages.ros.org/ros2/ubuntu is **3.6.0**, but I see that we have solved many problems and add new features. So It would be very helpful to update the package on http://packages.ros.org/ros2/ubuntu then we can use apt to install it.
Thanks.

**Comment by asasine** [comment]
Related: #417
