### ISSUE TITLE
How to use enum object as input variable in SwitchNode?

### ISSUE THREAD

**Issue by valaxkong** [BehaviorTree/BehaviorTree.CPP#436]
I have a SwitchNode like this.
![image](https://user-images.githubusercontent.com/18673335/192710454-5bbec989-1dcc-4ffd-8c39-a5662a5fc18b.png)
I need it switching according to an enumerate input variable {var}.
I have following code to cast the enum to int. 
```cpp
root_blackboard->set("var", (int)var_enum());
```
Finally, i got exception like this:
![image](https://user-images.githubusercontent.com/18673335/192711537-84d9ad95-e56d-4b97-9209-57da45cc5096.png)
How can I do this？Only string is supported as switch variable?

**Comment by facontidavide** [comment]
Can you send me code to reproduce this error?

**Comment by facontidavide** [comment]
Ideally, a failing unit test ;)

**Comment by facontidavide** [comment]
Reopen the issue once you provide an example I can run :)
