### ISSUE TITLE
XML parsing support for custom nodes are not executing properly -- issues with previously merged PR

### ISSUE THREAD

**Issue by najiib49** [BehaviorTree/BehaviorTree.CPP#441]
Hello everyone,

I've made a comment on a previously merged PR #194,  Where I was having trouble running Nav2 goal in rviz after editing and saving navigate_to_pose_w_replanning_and_recovery.xml file.  Since I haven't gotten a response, I thought I'd create a new issue for it. 

Here's my comment:

> Hi all!
> 
> I was learning behavior tree and was trying to add some dummy sequence node on `navigate_to_pose_w_replanning_and_recovery.xml` through Groot. I specifically added the sequence node on the navigation subtree of Navigate To Pose With Replanning and Recovery[¶](https://navigation.ros.org/behavior_trees/overview/detailed_behavior_tree_walkthrough.html#navigate-to-pose-with-replanning-and-recovery). In this sequence I tried to do two spins before pipelinesequence gets ticked.
> 
> Here's how my tree looks like
> 
> ![Screenshot from 2022-09-29 17-25-56](https://user-images.githubusercontent.com/38965572/193159434-fd2b6726-6e0e-4117-bee6-ccad04cfd2c1.png)
> 
> However, the problem I've faced was that when I saved this BT from groot, the underlying custom nodes in the xml changed into this parsing xml format mentioned in this PR. for example `<PipelineSequence name="NavigateWithReplanning">` changed to this `<Control ID="PipelineSequence" name="NavigateWithReplanning">` as well as all the other custom nodes.
> 
> When I run Nav2 and tried Nav2 goal in rviz, nav2 computes the path to pose but never follows that path. It just goes into the Recovery Subtree[¶](https://navigation.ros.org/behavior_trees/overview/detailed_behavior_tree_walkthrough.html#recovery-subtree). So I tried adding the sequence with the two spins by directly editing the navigate_to_pose_w_replanning_and_recovery.xml file instead of editing and saving it in Groot. I was able to achieve the behaviour I was looking for where the robot spins and then follows the computed path when Nav2 goal is selected in rviz.
> 
> I was wondering if anyone faced this issue when editing nav2 custom nodes in groot?
> 
> Note: this issue was persistent even when I loaded navigate_to_pose_w_replanning_and_recovery tree in groot and saved it without adding any additional nodes.

**Comment by facontidavide** [comment]
- Issues related to Groot should not be added here...
- And Groot 1 is going to be replaced by Groot 2, that doesn't have this issue...
- And that was discussed already here: https://github.com/ros-planning/navigation2/issues/3410#issuecomment-1433606388
