### ISSUE TITLE
error when running tutorial 3

### ISSUE THREAD

**Issue by laurafbec** [BehaviorTree/BehaviorTree.CPP#457]
> 
sorry @facontidavide! After reinstalling the library over Ubuntu 20.04 without the need to install Lexy lib, I continue with the error
`terminate called after throwing an instance of 'BT::RuntimeError'
  what():  Error at line 6: -> Node not recognized: SetBlackboard
Aborted (core dumped)
`
when testing tutorial 3.
Thanks again

_Originally posted by @laurafbec in https://github.com/BehaviorTree/BehaviorTree.CPP/issues/451#issuecomment-1293691246_

**Comment by facontidavide** [comment]
fixed
