### ISSUE TITLE
CMake is unable to find BehaviorTreeV3 since upgrading to v3.8

### ISSUE THREAD

**Issue by koonpeng** [BehaviorTree/BehaviorTree.CPP#461]
The latest release of BehaviorTree in ROS humble (version `3.8.0-1jammy.20221019.164714`) changed the package config file from `BehaviorTreeV3Config.cmake` to `behaviortree_cpp_v3Config.cmake`, this causes current projects using BehaviorTree via cmake's `find_package` to break.

**Comment by facontidavide** [comment]
sorry about that.

On the other hand... it seems like there is an easy fix, isn't it?

**Comment by koonpeng** [comment]
Yeah, it can be easily fixed by looking for `behaviortree_cpp_v3` instead. But given that this is not a major release, I thought this change is not intended.

**Comment by facontidavide** [comment]
I can understand you frustration, anyway that name was "wrong" in the first place...

Do you think it would be possible to add BOTH the names simultaneously? I mean adding (not replacing):

```
INSTALL(TARGETS ${BEHAVIOR_TREE_LIBRARY}
    EXPORT BehaviorTreeV3Config
    ARCHIVE DESTINATION ${BEHAVIOR_TREE_LIB_DESTINATION}
    LIBRARY DESTINATION ${BEHAVIOR_TREE_LIB_DESTINATION}
    RUNTIME DESTINATION ${BEHAVIOR_TREE_BIN_DESTINATION}
    )

install(EXPORT BehaviorTreeV3Config
    DESTINATION "${BEHAVIOR_TREE_LIB_DESTINATION}/BehaviorTreeV3/cmake"
    NAMESPACE BT::)

export(TARGETS ${PROJECT_NAME}
    NAMESPACE BT::
    FILE "${CMAKE_CURRENT_BINARY_DIR}/BehaviorTreeV3Config.cmake")
 
```

**Comment by facontidavide** [comment]
I think this is the solution to your problem.
I think that some ROS people will hate me, but that's life...

https://github.com/BehaviorTree/BehaviorTree.CPP/commit/4ddc0b035ca70547132ed5b90d9106a53bb46bc7

**Comment by facontidavide** [comment]
Sorry, but that doesn't work. if anybody with more knowledge about cmake wants to help he/she is very welcome.

I think the best course of action is to keep the new name **behaviortree_cpp_v3**
