### ISSUE TITLE
Behavior Tree CPP v3 spelling is wrong in latest ROS melodic distribution list. Possible breaking change?

### ISSUE THREAD

**Issue by swarajpeppermint** [BehaviorTree/BehaviorTree.CPP#465]
Seems like the spelling of behavior tree cpp v3 is incorrect in the latest melodic distribution list. Is this a breaking change for existing melodic Robotics Stacks? 
![image](https://user-images.githubusercontent.com/85288063/199665809-096088ff-2e93-4068-b6a7-918e85d6c447.png)

**Comment by facontidavide** [comment]
it has been like that since the beginning, and I never changed it

**Comment by facontidavide** [comment]
This issue will solve itself May 23rd 2023

http://wiki.ros.org/Distributions

Seriously though, people have been using the misspelled name all this time; if that is an issue, the safest option is to release a new package with the right name alongside the old one.
