### ISSUE TITLE
Suggestion about AsyncSequenceNode and AsyncReactiveSequenceNode

### ISSUE THREAD

**Issue by valaxkong** [BehaviorTree/BehaviorTree.CPP#466]
I have been using BehaviorTree.CPP to develop a robotic application for several months.
My behavior tree is reactive and non-reactive mixed. In the reactive part, I frequently meet a behavior pattern that is keepping checking a sequence of async conditions and/or excuting  a sequence of async actions. Specifically, asynchronous nodes means they could return RUNNING during one tick cycle.(Besides, I strongly agree with your renaming about AsyncActionNode as ThreadedAction in v4.0)
So I suggest an AsyncReactiveSequenceNode whose pseudo code is like this:
```cpp
NodeStatus AsyncReactiveSequenceNode::tick() {
    const size_t children_count = children_nodes_.size();

    setStatus(NodeStatus::RUNNING);

    while (current_child_idx_ < children_count) {
        TreeNode* current_child_node = children_nodes_[current_child_idx_];
        const NodeStatus child_status = current_child_node->executeTick();

        switch (child_status) {
            case NodeStatus::FAILURE: {
                haltChildren();
                current_child_idx_ = 0;
                return child_status;
            }
            case NodeStatus::RUNNING: {
                current_child_idx_++;  // Look at here!!!
            }
            case NodeStatus::SUCCESS: {
                current_child_idx_++;
                success_child_cnt_++;  // Look at here!!!
            } break;

            case NodeStatus::IDLE: {
                throw LogicError("A child node must never return IDLE");
            }
        }  // end switch
    }      // end while loop

    // The entire while loop completed. This means that all the children
    // returned SUCCESS.
    if (current_child_idx_ == children_count &&
        success_child_cnt_ == children_count) { // Look at here!!!
        haltChildren();
        current_child_idx_ = 0;
        success_child_cnt_ = 0;  // Look at here!!!
    }
    return NodeStatus::SUCCESS;
}


```
AsyncSequenceNode could be defined in a similar way.
I can give a PR if you think my suggestion is constructive.

**Comment by valaxkong** [comment]
Oh, sorry! I found ParallelNode can satisfy my requirement.

**Comment by valaxkong** [comment]
ParallelNode almost satisfy my requirement, but it has a skiplist mechanism. I think an AsyncSequenceNode mentioned above is still needed.

**Comment by facontidavide** [comment]
Assuming his error is obsolete/stale. Closing
