### ISSUE TITLE
Config error when trying to include library with FetchContent_Decalre

### ISSUE THREAD

**Issue by weagle08** [BehaviorTree/BehaviorTree.CPP#473]
I'd like to use this library, but when I try to get it with FetchContent_Declare/FetchContent_MakeAvailable I get the following error:
`CMake Error: install(EXPORT "behaviortree_cppTargets" ...) includes target "behaviortree_cpp" which requires target "lexy" that is not in any export set.`

**Comment by facontidavide** [comment]
Thanks a lot for reporting, that was a serious error
