### ISSUE TITLE
Broken catkin build and debian package 3.8.0 for ROS noetic

### ISSUE THREAD

**Issue by rcp1-beg** [BehaviorTree/BehaviorTree.CPP#478]
Hi,

the released version 3.8.0 for ROS 1 noetic (20.04) broke the catkin build by providing two cmake files with the same name:

```
lib/cmake/behaviortree_cpp_v3/behaviortree_cpp_v3Config.cmake <-- Generated by cmake configure_package_config_file
share/behaviortree_cpp_v3/cmake/behaviortree_cpp_v3Config.cmake <-- Generated by catkin
```

Catkin will find for dependent packages the first one, detect that behaviortree_cpp_v3 is not a proper catkin package and does not provide the standardized package variables. Thus, one needs to manually link BT::behaviortree_cpp_v3 with this release.

The problem was introduced with #379 as far as I can tell. One could wrap the manual `configure_package_config_file` in the CMakeLists.txt with `if(NOT catkin_FOUND)` as simplistic fix.

Thanks for looking into it!

**Comment by facontidavide** [comment]
Just to be sure, what is your level of confidence on the solution that you mention will work and it will not brake the behavior for others?

**Comment by facontidavide** [comment]
Should be fixed. I am bloom-ing soon

**Comment by rcp1-beg** [comment]
Thank you very much for the fix. Sorry that I did not answer your question, I was on vacation...
