### ISSUE TITLE
[v3.8.1] [Bug]: Including subtrees with the "ros_pkg" attribute is broken for ROS1

### ISSUE THREAD

**Issue by Lnsrini** [BehaviorTree/BehaviorTree.CPP#484]
- For ROS1 packages, the `ros_pkg` attribute of the `<include>` tag can no longer be used to specify a path to a Subtree.
- [**This commit**](https://github.com/BehaviorTree/BehaviorTree.CPP/commit/a55c1cee06097327ec15793461d8237e63b3377f) is probably the one which we believe introduced the problem 
- Problem was found when we made the upgrade from to v3.8.1 and probably remains in v3.8.2

**Comment by Lnsrini** [comment]
Just now realized there is already an open PR for the fix: https://github.com/BehaviorTree/BehaviorTree.CPP/pull/483

**Comment by Lnsrini** [comment]
Good day @facontidavide ! Do you have time to take a look at the linked [commit](https://github.com/BehaviorTree/BehaviorTree.CPP/commit/a55c1cee06097327ec15793461d8237e63b3377f) and [open PR](https://github.com/BehaviorTree/BehaviorTree.CPP/pull/483) for the fix?
This currently breaks existing behavior for ROS1 packages.

**Comment by rcp1-beg** [comment]
@facontidavide Would this fix be enough to reason a new release for ROS 1 (3.8.3)? :)
