### ISSUE TITLE
I can't find BT::StatefulAsyncAction.

### ISSUE THREAD

**Issue by jwson97** [BehaviorTree/BehaviorTree.CPP#485]
Hi, I am new to Behavior tree so I follow the tutorials (v4.0).

In Tutorials - Basics 04. Reactive behaviors. 

`class MoveBaseAction : public BT::StatefulAsyncAction`

I got the error in `BT::StatefulAsyncAction. `

I tried to find BT::StatefulAsyncAction in http://docs.ros.org/en/kinetic/api/behaviortree_cpp_v3/html/namespaceBT.html

But I can't find BT::StatefulAsyncAction too. 

I just can find BT::StatefulActionNode. 
But I am not sure this class performs async operation. 

Please let me know if I'm doing something wrong or if I'm misunderstanding something.

**Comment by grammers** [comment]
I have the same issue, to me, it appears as if BT::StatefulAsyncAction only exists in the tutorials (Reactive and Asynchronous behaviors, and Asynchronous Actions).

**Comment by facontidavide** [comment]
Documentation fixed!
