### ISSUE TITLE
Passing a variable (string) to the behavior tree from external source.

### ISSUE THREAD

**Issue by Naraharirahul** [BehaviorTree/BehaviorTree.CPP#491]
Hi, 

I have a behavior tree which is similar to the one shown below. I use docker containers to run and launch nodes.
I want to pass a string as a variable to the tree from my docker-compose file so that I can chose between different setups.
Is there any way I can get this easily?

```
<Switch2 variable="{window_number}" case_1="window_1" case_2="window_2">
    <Action ID="OpenWindow" door="window_1"/>
    <Action ID="OpenWindow" door="window_2"/>
    <Action ID="OpenWindow" door="none"/>
</Switch2>
```

In the above example, I want to set the value of the `window_number` variable from docker-compose file.

**Comment by facontidavide** [comment]
First, it is not clear to me why you can't write the code as:

```xml
<OpenWindow door="{window_name}"/>
```
In terms of Docker, the first solution that comes to mind is to use environment variables. Some configuration file is also possible.

For instance, if you had an environment variable called **WindowID** 

```xml
<Sequence>
    <LoadEnvironmentVariable var="WindowID" out="{window_name}"/>
    <OpenWindow door="{window_name}"/>
</Sequence>
```

`LoadEnvironmentVariable` doesn't exist but is trivial to implement.

You can also preload variables into the blackboard of the tree.

```cpp
auto bb = Blackboard::create();
bb->set("window_name", "window1");
auto tree = factory.createTree("MyTreeName", bb);
```

If you have further questions, let me know.
