### ISSUE TITLE
When I build the System, I encounter the following erro

### ISSUE THREAD

**Issue by robertokcanale** [BehaviorTree/BehaviorTree.CPP#492]
Hello, I am trying to run a simple project while following the documentation.

**Comment by robertokcanale** [comment]
I get tht following code after running 
`cmake ..
`inside the build folder

```
-- Configuring done
CMake Error at CMakeLists.txt:8 (add_executable):
  Target "BT_tutorials" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:8 (add_executable):
  Target "BT_tutorials" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by yendiDev** [comment]
> I get tht following code after running `cmake .. `inside the build folder
> 
> ```
> -- Configuring done
> CMake Error at CMakeLists.txt:8 (add_executable):
>   Target "BT_tutorials" links to target "Threads::Threads" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> CMake Error at CMakeLists.txt:8 (add_executable):
>   Target "BT_tutorials" links to target "Threads::Threads" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> 
> 
> -- Generating done
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> ```

Same error

**Comment by facontidavide** [comment]
Is this **main** branch? I will have a look

**Comment by facontidavide** [comment]
Can your confirm your build system? catkin/ colcon/ vanilla cmake ?

**Comment by facontidavide** [comment]
hello?

**Comment by yendiDev** [comment]
Hi,
I have not worked on this in a while. 
I will boot up the project and communicate over the weekend

**Comment by mnumanuyar** [comment]
I have the same error. this might be relevant : https://stackoverflow.com/questions/60227678/cmake-throws-error-during-generation-when-building-openpose-library

**Comment by mnumanuyar** [comment]
tobe presice i get this error not during cmake of BT but during cmake of a dummy project that uses BT. error is :  
```
-- Configuring done
CMake Error at /usr/local/lib/cmake/behaviortree_cpp/behaviortree_cppTargets.cmake:61 (set_target_properties):
  The link interface of target "BT::behaviortree_cpp" contains:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/local/lib/cmake/behaviortree_cpp/behaviortree_cppConfig.cmake:27 (include)
  CMakeLists.txt:6 (find_package)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by facontidavide** [comment]
Pushed a solution
