### ISSUE TITLE
Recommended behavior tree editor?

### ISSUE THREAD

**Issue by mjeronimo** [BehaviorTree/BehaviorTree.CPP#5]
I see on your site that you have a screenshot of a Behavior Tree editor. Do you happen to have a recommendation of which to use? I'd like to output XML that can be used w/ the BehaviorTree.CPP library to automatically construct the tree. Also, of course, I'd have to be able to add custom nodes to the editor so that they can be placed in the tree and parameters for each action specified. It would be nice, too, to be able to actually run the BTs from the UI.

**Comment by facontidavide** [comment]
The recommended editor is Groot https://github.com/BehaviorTree/Groot

The only "problem" that makes it a pre-alpha is the somehow cumbersome way to create new custom Actions ( I will fix it in November).

Right now custom TreeNodes can be added to the palette of Groot only through XML file. 

Furthermore, the GUI is not meant to contain the executor as well. They should remain two different processes that communicate in real-time thought TCP.

I have to write some documentation to show how this work. I hope to have it by the end of Novemeber.

Cheers

**Comment by facontidavide** [comment]
To get an idea of how Groot works, you can take a look at the Vimeo channel https://vimeo.com/manage/albums/5201743

**Comment by mjeronimo** [comment]
Thanks for the info and the pointer to the video. Can you add me to the permissions to that Vimeo folder so that I can view the video?

**Comment by facontidavide** [comment]
edited the link, my bad

**Comment by facontidavide** [comment]
The readme clearly points out to Groot. I will close this
