### ISSUE TITLE
Run with RTOS on MCU?

### ISSUE THREAD

**Issue by ymei** [BehaviorTree/BehaviorTree.CPP#500]
Is it possible to run this with an RTOS (FreeRTOS?) on a microcontroller such as STM32?  Any existing examples?

**Comment by facontidavide** [comment]
Hi,
Even if BehaviorTree.CPP is supposed to be lightweight, I am not aware of the amount of memory that it requires and the potential problems it may have in the context of MCU.

So, the general answer is ... maybe? No existing examples.

On top of my head, that would probably require having a look at the way std::string is used and XML parsing should be probably stripped down, to use code generation instead.

That would is a project that I would not be able to do, unless some company is willing to pay for that development.

**Comment by ymei** [comment]
Thanks for clarifying this.  MCU is a space where state machines proliferate.  BT surely will make a difference.  Code generation sounds worth a try.
