### ISSUE TITLE
Suggestion: register custom node without static ports list

### ISSUE THREAD

**Issue by kubakaminski** [BehaviorTree/BehaviorTree.CPP#501]
Could you provide a possibility to register a custom node (using registerNodeType method) with additional arguments and without static ports list? As far as i understand it is not possible now: 
Here you can provide a list, but without arguments
```
  template <typename T>
  void registerNodeType(const std::string& ID, PortsList ports)
  {
    ...

    registerBuilder(CreateManifest<T>(ID, ports), CreateBuilder<T>());
  }
```
But here you can provide additional arguments but without a list
```
     */
  template <typename T, typename... ExtraArgs>
  void registerNodeType(const std::string& ID, ExtraArgs... args)
  {
    ...

    registerBuilder(CreateManifest<T>(ID), CreateBuilder<T>(args...));
  }
```

**Comment by facontidavide** [comment]
that method exist already:  https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp/bt_factory.h#L209-L216

Unfortunately, not the most usable one and requires some boiler plate from you side.

**Comment by facontidavide** [comment]
fixed. Also some code duplication removed
