### ISSUE TITLE
Suggestion: Add a unique id to log

### ISSUE THREAD

**Issue by ct2034** [BehaviorTree/BehaviorTree.CPP#503]
I am using the https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/tools/bt_log_cat.cpp to display the log. But when there are two nodes with the same name on the same level, it is hard to know which one it is, when viewing the log. So my suggestion would be to show the UID in the output, too.

**Comment by facontidavide** [comment]
sounds as a good idea. Consider that in version 4.1, there is a new string identifier that aims to be unique, but I think this change looks good

**Comment by ct2034** [comment]
Thanks, @facontidavide ! And a unique String ID also sounds like a very good idea. 
Btw, #502 implements this one
