### ISSUE TITLE
'std::bad_alloc' when using Script node on Raspberry Pi (32 bit)  + possible fix

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/BehaviorTree.CPP#505]
Running the following tree:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root BTCPP_format="4">
  <BehaviorTree ID="MainTree">
    <Sequence>
      <Script code="var:='Hello, world'"/>
    </Sequence>
  </BehaviorTree>
</root>
```

results in this error:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

I did some debugging and was able to fix this by changing this line in simple_string.hpp:
```cpp
constexpr static std::size_t CAPACITY = sizeof(void *) * 2 - 1;
```
to this:
```cpp
constexpr static std::size_t CAPACITY = 15;
```

On arm32, `sizeof(void *)` returns 4, so CAPACITY was set to 7.

I'm not sure if this is correct solution, but it seems to work so far.

**Comment by facontidavide** [comment]
solution pushed, thanks for reporting. if you have further problems, let me know
