### ISSUE TITLE
Build issue with 4.0.2

### ISSUE THREAD

**Issue by bektaskemal** [BehaviorTree/BehaviorTree.CPP#508]
Hi,
At https://github.com/BehaviorTree/BehaviorTree.CPP/commit/804552a792c5a75fc47ebc2e32b55060cfcbc90b you removed default value for portlist in CreateManifest. But it is called without portlist  here: 
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/804552a792c5a75fc47ebc2e32b55060cfcbc90b/include/behaviortree_cpp/bt_factory.h#L213

I think it could be breaking for the people using that version of registerBuilder.

**Comment by facontidavide** [comment]
Great point. Reverted 
https://github.com/BehaviorTree/BehaviorTree.CPP/commit/1bb86ce70b2d245dd182f5c505f72698b33e5c0e
