### ISSUE TITLE
"ReactiveSequence is not supposed to reach this point" happens when some children are skipped

### ISSUE THREAD

**Issue by torydebra** [BehaviorTree/BehaviorTree.CPP#515]
Hi,
I am using a ReactiveSequence with `_skipIf` preconditions on the children, and it throws:
```
terminate called after throwing an instance of 'BT::LogicError'
  what():  ReactiveSequence is not supposed to reach this point
```

Looking at the code https://github.com/BehaviorTree/BehaviorTree.CPP/blob/109eccd29f8cc4a872b27c8a64096589b3bd9f73/src/controls/reactive_sequence.cpp#L54-L72

it seems that this happens because if a children is `SKIPPED` the `success_count` is not increased, neither the method returns, ending in the throw. Am I right? 

I can provide simple example if necessary to replicate this

**Comment by facontidavide** [comment]
yes, a simple example would be really great. I will fix this as soon as I receive it

**Comment by facontidavide** [comment]
Fixed. Thank for reporting
