### ISSUE TITLE
Wrong language for code block in the documentation 

### ISSUE THREAD

**Issue by ErickKramer** [BehaviorTree/BehaviorTree.CPP#516]
Hi,
First of all, thank you for taking the time and effort of generating such a nice documentation for the library!.

While I was reading through the documentation, I noticed that the last three code blocks in the [asynchronous_nodes](https://www.behaviortree.dev/docs/tutorial-advanced/asynchronous_nodes) tutorial have the wrong language defined.

The code block properly rendered is using `language-cpp`, while the other three have `language-c++`

**Comment by facontidavide** [comment]
thanks, i will fix it
