### ISSUE TITLE
Halting the tree doesn't set the root node to idle

### ISSUE THREAD

**Issue by DonDoff** [BehaviorTree/BehaviorTree.CPP#517]
Hello, 

I would like to know why halting the tree (`tree.haltTree())`) is longer setting the root node to idle?
This used to be the case before, and I'm wondering why that changed. 
This was changed in commit 84422ffe9de2e245d1cc7160aaea0ba90e8ce301.

And if it was intentional, what would then be the way to "reset" a tree to IDLE?

**Comment by facontidavide** [comment]
I can change that. I think it is reasonable to expect root node to be IDLE after an halt
