### ISSUE TITLE
build failed on vs2022 

### ISSUE THREAD

**Issue by FJSDS** [BehaviorTree/BehaviorTree.CPP#527]
Windows 11 1000.22000.1696.0
VS2022 17.5.2

![image](https://user-images.githubusercontent.com/10356979/225818455-85f540d1-2e99-48c1-bce9-4ac45f6350a5.png)

![image](https://user-images.githubusercontent.com/10356979/225822363-e048cc0e-f559-4154-b508-a0cf5f551da7.png)

**Comment by facontidavide** [comment]
It looks like you are trying to compile version 3?

Why not 4?

**Comment by facontidavide** [comment]
Closing this being based on a old version ofthe library
