### ISSUE TITLE
about the order of asynchronous execution

### ISSUE THREAD

**Issue by zouyuxuan** [BehaviorTree/BehaviorTree.CPP#534]
I created the behavior tree in sequential mode, action node A uses **asynchronous**, why does the behavior tree wait until action A is executed before executing other nodes.
![image](https://user-images.githubusercontent.com/33485252/227080345-52556ff4-80cd-43e9-9647-ad3acacb485d.png)
actual output
![image](https://user-images.githubusercontent.com/33485252/227080165-69777057-b92f-4273-a4b3-c0ea1771149a.png)
Why isn't output 
**action_A: Started. Send Request to server.**
 **Robot says: The answer is 42**
 **action_A: Done. 'Waiting Reply' loop repeated 929 times
action_A: cleaning up after SUCCESS**

**Comment by facontidavide** [comment]
Your output is correct. Sequence will wait for 3rd children (`MyAsyncAction`)  to complete and return SUCCESS or FAILURE, before moving on with 4th and 5th children.

This is intended behavior.

About your halting of action_A, if you are not in RUNNING state, that should be a no-op
