### ISSUE TITLE
How to compile in a development environment that does not support conan?

### ISSUE THREAD

**Issue by yaobyron** [BehaviorTree/BehaviorTree.CPP#535]
As the title. 
Thanks

**Comment by yaobyron** [comment]
I can write Cmakelists.txt by myself. But it cannot be directly compiled as a three-party library like v3.8.

**Comment by facontidavide** [comment]
Do you want to have ZeroMQ support?

In the [dev branch](https://github.com/BehaviorTree/BehaviorTree.CPP/tree/dev ) I am adding options to enable/disable dependencies.

If you don't want to use conan, you should have ZeromMQ and SQlite3 installed in your system, or disable those options

**Comment by facontidavide** [comment]
Please check that branch and let me know if latest commit solves your issue

**Comment by facontidavide** [comment]
fixed in master. README updated
