### ISSUE TITLE
Multiple statements in the precondition

### ISSUE THREAD

**Issue by kubakaminski** [BehaviorTree/BehaviorTree.CPP#536]
Hello, I'm trying to check multiple statements in the precondition of a node. Looks like the library fails to parse it and always skips this node.
The precondition looks like this (Groot2):
![image](https://user-images.githubusercontent.com/110972183/227884838-27ab2f29-b79b-4ffd-9634-df23da6b2fc8.png)

When there is only one statement in the precondition (eg. "use_case!='A'") it works.

**Comment by facontidavide** [comment]
I think your logic statement is wrong

how can this statement can possibly be false? it is impossible

**Comment by kubakaminski** [comment]
You are absolutely right, after fixing it is working as intended. I can't believe I didn't notice that :)
