### ISSUE TITLE
Arithmetic operations on Post Conditions (Success | Failure) | Not working

### ISSUE THREAD

**Issue by ephson24** [BehaviorTree/BehaviorTree.CPP#539]
Hi Davide,

I find trying to set arithmetic operations using **_onSuccess** and **_onFailure** does not work.
However using **_onpost** works as expected.

E.g XML (not working)
```
<Sequence>
              <TestCanDo state="false"
                         _onFailure="loop_count  += 1"/>
              <SendWarning deviceStatus="{isLowBattery}"
                           deviceType="BATT"/>
</Sequence>
``` 
But this works:
```
<Sequence>
              <TestCanDo state="false"
                         _onpost="loop_count  += 1"/>
              <SendWarning deviceStatus="{isLowBattery}"
                           deviceType="BATT"/>
</Sequence>
``` 

C++ code
```c++
BT::NodeStatus testCanDo(BT::TreeNode &self)
{
  bool state;
  if(auto res = self.getInput<bool>("state"))
    state = res.value();
  else
    throw std::runtime_error(res.error());
  return (state)? BT::NodeStatus::SUCCESS : BT::NodeStatus::FAILURE;
}
``` 

Could this be a bug of sorts?

PS: **TestCanDo** is a simple condition node

**Comment by ephson24** [comment]
Solved by removing the spacing between the variable and arithmetic operations
**Solution**
```
<Sequence>
              <TestCanDo state="false"
                         _onFailure="loop_count+=1"/>
              <SendWarning deviceStatus="{isLowBattery}"
                           deviceType="BATT"/>
</Sequence>
```

**Comment by facontidavide** [comment]
That is still a bug, even with spacing, it should work.

**Comment by facontidavide** [comment]
I added a specific unit test for your case, but can not reproduce the error:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/tests/gtest_postconditions.cpp#L41-L62

Closing. If youcan create a variant of the unit test that show the issue, let me know
