### ISSUE TITLE
Listening to topics in Conditions

### ISSUE THREAD

**Issue by gbcarlos** [BehaviorTree/BehaviorTree.CPP#541]
Is there a standardized way on how to implement conditions that listen to topics? I found several issues that target the same but none documented this clear enough.

Using v3.8 under ROS Noetic.

**Comment by facontidavide** [comment]
Please look at the ROS2 implementation: 

https://github.com/BehaviorTree/BehaviorTree.ROS2/blob/humble/behaviortree_ros2/include/behaviortree_ros2/bt_topic_sub_node.hpp
