### ISSUE TITLE
CMake variable BTCPP_LIBRARY has not been set

### ISSUE THREAD

**Issue by Hadi-Hajieghrary** [BehaviorTree/BehaviorTree.CPP#558]
After installing the BehaviorTree.cpp with "make install", the following in the CMakeList.txt returns empty for ${BTCPP_LIBRARY}", and the code is not linking:

find_package(behaviortree_cpp REQUIRED)
message("BTCPP_LIBRARY is ${BTCPP_LIBRARY}")

Suggested Fix:

adding the following to the CMakeList.txt fixes the problem:

set(BTCPP_LIBRARY "/usr/local/lib/libbehaviortree_cpp.so")

Later, I am using the ${BTCPP_LIBRARY} in include_directories(${PROJECT_NAME} PUBLIC include ${BTCPP_LIBRARY}).

(Ubuntu 22 LTS)

**Comment by ipa-rar** [comment]
```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.5)
project(bt_example)

set(CMAKE_CXX_STANDARD 17)

find_package(behaviortree_cpp REQUIRED)

add_executable(bt_example main.cpp)
target_link_libraries(bt_example /usr/local/lib/libbehaviortree_cpp.so)
```
This CMakeLists.txt would work for basic users
