### ISSUE TITLE
Core dump on example code

### ISSUE THREAD

**Issue by guzhaoyuan** [BehaviorTree/BehaviorTree.CPP#564]
I combined the latest master code successfully for Ubuntu 20.04 with ROS1, catkin build, GCC9. When I run the executables, however, all of them give me a segmentation fault (core dump). As seen in the figure.
![Screenshot from 2023-05-15 16-08-41](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/11495993/8b5b29da-ddb3-4546-9c3a-11e68a8ef7b9)

When I checked out to v4.1.1, the issue went away.

**Comment by facontidavide** [comment]
thanks for reporting
