### ISSUE TITLE
Optional ports for the node

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/BehaviorTree.CPP#576]
Hi. I couldn't find information about possibility of specifying optional input ports for the node.

For example, I have a node with 4 input ports, but only two of them accept different values most of the time, and other two ports are rarely changing. So, I would like to be able to omit those ports when creating a tree and only set them when I need to override the default values.

The main goal which I'm trying to achieve here is to minimize the number of hard coded values, so I could easily change default values for certain ports without modifying each tree, where the port is set.

**Comment by OPerepadia** [comment]
Currently I'm able to omit certain ports, and it works when executing tree, but Groot 2 is showing an error like this:

>Node '1130' expected a port with name 'min_speed', but not found in the XML

So I started looking for a better solution.

**Comment by facontidavide** [comment]
If the port has a default value, that error message should not be displayed in Groot2.
let me see if I need to fix that

**Comment by facontidavide** [comment]
Here there is an example of ports with default values

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp/controls/parallel_node.h#L49-L53

You need to use this function overload:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp/basic_types.h#L351-L354

Groot2 should not complain, in that case. Let me double check

**Comment by OPerepadia** [comment]
Yes, this works, not sure how I missed the default values. Thanks!

**Comment by OPerepadia** [comment]
@facontidavide I apologize for commenting on a closed topic, but I believe this issue is related.
I'm trying to set default values for the generic types from tutorial 3.
This example code compiles and works as expected:
```cpp
InputPort<Position2D>("target", description)
```

But this one produces an error - no matching function for call to ‘to_string(BT::Position2D&)’
```cpp
InputPort<Position2D>("target", {1.0, 2.0}, description),
```

Is this not implemented or am I doing something wrong?
