### ISSUE TITLE
Default values for ports with generic types

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/BehaviorTree.CPP#580]
I would like to set default values for ports with generic types.

This code from tutorial 3 compiles and works as expected:
```cpp
return {InputPort<Position2D>("target", description)};
```

But this one produces an error - no matching function for call to ‘to_string(BT::Position2D&)’
```cpp
return {InputPort<Position2D>("target", {1.0, 2.0}, description)};
```

Is this not implemented or am I missing something in my code?

**Comment by OPerepadia** [comment]
Solved. I added `toStr` function so it knows how to convert this type back to string, and now it compiles and works as expected.

```cpp
template <>
inline std::string toStr<Position2D>(Position2D value) {
    std::ostringstream ss;
    ss << value.x << ";" << value.y;
    return ss.str();
}
```

**Comment by OPerepadia** [comment]
@facontidavide Maybe we should include this function in the tutorial?

**Comment by facontidavide** [comment]
interesting, I would say that this is **almost** a bug. Let me add a more useful error message

**Comment by facontidavide** [comment]
changed the message error to be more useful

**Comment by facontidavide** [comment]
Sooooo...
The solution to this problem was finally more complicated that I expected.

I have a new branch v4.3, where I implemented a considerable improvement of the default value for custom types.

You may try that, if you want.
