### ISSUE TITLE
Pre condition is ignored by CoroActionNode

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/BehaviorTree.CPP#585]
I have the following tree:
```xml
<BehaviorTree ID="MainTree">
    <Sequence>
      <Teleop _skipIf="1"/>
    </Sequence>
</BehaviorTree>
```

The node `Teleop` has type CoroActionNode, and is executed regardless of whether `_skipIf` is set to 0 or 1.

However, if I specify the same pre condition for Sequence, it works, and `Teleop` node is not executed.

```xml
<BehaviorTree ID="MainTree">
    <Sequence _skipIf="1">
        <Teleop/>
    </Sequence>
</BehaviorTree>
```

**Comment by facontidavide** [comment]
Thanks for reporting, I will check this and come back to you with a solution

**Comment by facontidavide** [comment]
Fixed and unit test added :smile:

**Comment by OPerepadia** [comment]
Yes, works now.  Thanks!
