### ISSUE TITLE
BT.CPP 4.3.0 RetryUntilSuccessful and the 'skip' precondition

### ISSUE THREAD

**Issue by kd-ufr** [BehaviorTree/BehaviorTree.CPP#587]
Hi Davide,

I've been playing around with reactive sequences and retry until successful decorators, and I've come across an odd situation: the skip precondition is not applied to RetryUntilSuccessful node within a Reactive Sequence.

I've included an example below:
```
  <BehaviorTree ID="Example A">
    <Sequence>
      <Script code="test := false"/>
      <ReactiveSequence>
        <RetryUntilSuccessful name="Retry 1"
                              num_attempts="-1"
                              _skipIf="test ">
          <AlwaysSuccess name="Success 1"
                         _onSuccess="test = true"/>
        </RetryUntilSuccessful>
        <RetryUntilSuccessful name="Retry 2"
                              num_attempts="-1">
          <AlwaysFailure name="Failure 2"/>
        </RetryUntilSuccessful>
      </ReactiveSequence>
    </Sequence>
  </BehaviorTree>
```

In Example A, I expect the tree to tick Retry 1 and Success 1 once, and then skip them in subsequent ticks of the tree. However, they are continually ticked even though the skip precondition is now true.

```
Sequence                  IDLE -> RUNNING
Script                    IDLE -> SUCCESS
ReactiveSequence          IDLE -> RUNNING
Retry 1                   IDLE -> RUNNING
AlwaysSuccess             IDLE -> SUCCESS
AlwaysSuccess             SUCCESS -> IDLE
Retry 1                   RUNNING -> SUCCESS
Retry 2                   IDLE -> RUNNING
Failure 2                 IDLE -> FAILURE
Failure 2                 FAILURE -> IDLE
Retry 1                   SUCCESS -> RUNNING
AlwaysSuccess             IDLE -> SUCCESS
AlwaysSuccess             SUCCESS -> IDLE
Retry 1                   RUNNING -> SUCCESS
Failure 2                 IDLE -> FAILURE
Failure 2                 FAILURE -> IDLE
Retry 1                   SUCCESS -> RUNNING
repeat ad nauseam
```

This is because the RetryUntilSuccessful node transfers straight from SUCCESS into RUNNING. It's never set to IDLE, so the skip precondition is never triggered. I was wondering why this node is never reverted to IDLE so the precondition can be applied? The documentation explains the skip precondition as "Skip the execution of this Node, if the condition is true". I would have assumed that the precondition would be reevaluated after the node finished executing (regardless of SUCCESS or FAILURE) and began re-executing, as the docs don't mention it is only applicable in an IDLE state. I understand if my interpretation is incorrect; is there a way to 'force' this node back to IDLE so it's preconditions can be reapplied?

Thanks for your help :)

**Comment by SteveMacenski** [comment]
^ adding a description might be useful friend :-)

**Comment by kd-ufr** [comment]
fat fingers! I'm editing now sorry

**Comment by facontidavide** [comment]
Even if I think that you might have found a bug (thanks!) at the logical level, this tree makes no sense, because you will **ALWAYS** have an infinite loop in "Retry 2".

> In Example A, I expect the tree to tick Retry 1 and Success 1 once, and then skip them in subsequent ticks of the tree. 

In that case, there is no one stopping this code from executing forever:

``` xml
<RetryUntilSuccessful name="Retry 2"    num_attempts="-1">
          <AlwaysFailure name="Failure 2"/>
</RetryUntilSuccessful>
``` 

Anyway, I agree that, even if the logic itself seems wrong, "Retry 1" should be executed once. I will fix it.

**Comment by kd-ufr** [comment]
Thanks for getting back to me. And yes, Retry 2 is an infinite loop. In my working code I have a big subtree that returns RUNNING, but I was trying to make a small runable example to demonstrate the behaviour I was seeing. Thanks again.

**Comment by facontidavide** [comment]
Push fixed. thanks for reporting
