### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Lecrapouille** [BehaviorTree/BehaviorTree.CPP#589]
The compilation steps in the README do not seem correct.

```
mkdir build; cd build
conan install ../BehaviorTree.CPP --output-folder=. --build=missing
cmake ../BehaviorTree.CPP -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --parallel
```

The correct steps are:
```
mkdir build; cd build
conan install .. --output-folder=. --build=missing
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --parallel
```

**Comment by SteveMacenski** [comment]
You can submit that as a PR you know :smile:

**Comment by Lecrapouille** [comment]
@SteveMacenski For such simple changes PRs are overkill but I made one :)

**Comment by SteveMacenski** [comment]
I disagree, but not providing the PR, you're making a simple change that Davide could just hit "merge" on into something he has to himself make the changes onto and PR himself. You've already identified the patch, by submitting the PR you're saving everyone time in the long run

**Comment by facontidavide** [comment]
I think that:
- You missed the line "Assuming that you are in the **parent** directory of `BehaviorTree.CPP`"
- I used "../" instead of "./"

**Comment by Lecrapouille** [comment]
Correct ! I was more accustomed to have the build folder inside the project
