### ISSUE TITLE
BT.CPP 4.3.0 Can't use remapped value in precondition

### ISSUE THREAD

**Issue by kd-ufr** [BehaviorTree/BehaviorTree.CPP#592]
Hi Davide,

I'm having trouble using subtree remapped values in preconditions. It seems like if a remapped value is not used in a node port, it cannot be used in a precondition. I've included some examples.

I expect this example to tick the AlwaysSuccess node in Inner Tree A.
```
  <BehaviorTree ID="Outer Tree A">
    <Sequence>
      <Script code="variable := 'test'"/>
      <SubTree ID="Inner Tree A"
               variable="{variable}"
               _autoremap="false"/>
    </Sequence>
  </BehaviorTree>

  <BehaviorTree ID="Inner Tree A">
    <Sequence>
      <AlwaysSuccess _skipIf="variable != 'test'"/>
    </Sequence>
  </BehaviorTree>
```

However, Outer Tree A crashes when it reaches the AlwaysSuccess node with the error `what():  Variable not found: variable`. Setting autoremap to true doesn't fix this. 

In this example I'd expect both children in Inner Tree B to be ticked. The PrintString node takes a string input and prints to the terminal.

```
  <BehaviorTree ID="Outer Tree B">
    <Sequence>
      <Script code="variable := 'test'"/>
      <SubTree ID="Inner Tree B"
               variable="{variable}"
               _autoremap="false"/>
    </Sequence>
  </BehaviorTree>

  <BehaviorTree ID="Inner Tree B">
    <Sequence>
      <AlwaysSuccess _skipIf="variable != 'test'"/>
      <PrintString key="{variable}"/>
    </Sequence>
  </BehaviorTree>
```

This example succeeds. Interestingly it doesn't require `variable` to be used in a port before it is used in the precondition - it just needs to be used in a port at some point during the subtree. 

Is this just how subtrees work? I can put PrintString nodes in my subtrees so all values are remapped, but this doesn't seem like a great solution.

Thanks for your help :)

**Comment by facontidavide** [comment]
solution pushed to master. Thanks for reporting :smiley:
