### ISSUE TITLE
 Compilation failed

### ISSUE THREAD

**Issue by Frp529** [BehaviorTree/BehaviorTree.CPP#600]
According to the document to compile and received the following error.
"ERROR: Error reading 'C:\Users\Richard\.conan2\profiles\cura_build.jinja' profile: ConfigParser: Unrecognized field 'build_requires'
"

cura_build.jinja
include(default)

[build_requires]

[settings]
compiler.cppstd=17
{% if compiler == 'gcc' %}compiler.libcxx=libstdc++11
{% elif compiler == 'apple-clang' %}compiler.libcxx=libc++
{% elif compiler == 'Visual Studio' %}compiler.toolset=v142
{% endif %}
[options]

[env]

[conf]

**Comment by facontidavide** [comment]
This is a problem with your conan profile, not with the library

![image](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/2822888/e965f7af-1bbb-4a32-a691-89a9bde2bbb9)
