### ISSUE TITLE
Consider adding node description that can be auto-generated to `tree_nodes_model.xml`

### ISSUE THREAD

**Issue by sea-bass** [BehaviorTree/BehaviorTree.CPP#603]
Right now, we can automatically generate a `tree_nodes_model.xml` manifest from our registered nodes, which includes default values and descriptions for ports.

However, one thing that is missing is a node-level description that can be added to the manifest like so:

```xml
    <Action ID="SomeActionNode">
        <description>This is the node description we want to add.</description>
        <input_port name="input_val" default="123">Input port description.</input_port>
        <output_port name="output_val" default="45">Output port description.</output_port>
    </Action>
```

Is there some way that we can add description metadata to a node so that we can generate such a node description? If so, how should we do it?

**Comment by facontidavide** [comment]
DONE.

have a look at this:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/tests/gtest_factory.cpp#L374-L405
