### ISSUE TITLE
Passing Class Shared Ptr through Node Builder

### ISSUE THREAD

**Issue by varungiridhar** [BehaviorTree/BehaviorTree.CPP#606]
#### Description
Here is my current BehaviorTree nodebuilder; I wanted to assess whether there was any risk in passing a class shared pointer through the Node Builder in BehaviorTree.cpp?

```cpp
// MyClass:
class MyClass {
    // getters for private member variables
    
private:
   // member variables populated via ROS subscribers
}
```
```cpp
std::shared_ptr<MyClass> class_shared_ptr = std::make_shared<MyClass>();
factory_.registerBuilder<NodeType>(id,
      [&my_class_shared_ptr](const std::string& name, const BT::NodeConfiguration& config) {
        return std::make_unique<NodeType>(name, config, my_class_shared_ptr);
      });
```

```cpp
class Node : public StatefulActionNode {
public:
    Node(const std::string& name, const BT::NodeConfiguration& config, std::shared_ptr<PumaBTAllocator> my_class_shared_ptr) {
    auto variable = my_class_shared_ptr->getMemberVariable()
    // do stuff with variable
}

}
```
My goal with this design is to access updated member variable data from MyClass in the Behavior Tree Nodes. And passing the entire class as a shared pointer saves me the hassle of handpicking what variables I want to pass through the builder.

Is there any risk to building out the interface this way? 

Thank you,
Varun

**Comment by facontidavide** [comment]
No problem, but the easier way would be to follow [Tutorial 8](https://www.behaviortree.dev/docs/tutorial-basics/tutorial_08_additional_args)
