### ISSUE TITLE
Question: Is there anyway to use the BT with ROS1 noetic?

### ISSUE THREAD

**Issue by MithunKinarullathil** [BehaviorTree/BehaviorTree.CPP#626]
Currently, the documentation explains how to integrate BT with ROS2, Is there any way to use this with ROS1? Thanks.

**Comment by tony-p** [comment]
Yes it is supported. There is a CI pipeline to test building with ROS1 and ROS2, and further it is not in itself linked to ROS in any way. There is a package also for ROS1 bindings (don't know the status) but you can always create the bindings yourself as they just implement some of the boiler plate to call the actions/services/topics for you from a BT action

https://github.com/BehaviorTree/BehaviorTree.ROS

**Comment by MithunKinarullathil** [comment]
@tony-p Thanks.
