### ISSUE TITLE
[Question] BehaviorTree.CPP v3.8, bt_factory.h

### ISSUE THREAD

**Issue by prof-concert** [BehaviorTree/BehaviorTree.CPP#642]
Hello,
I had a question regarding the bt_factory.
I used registerBehaviorTreeFromText to register my dynamic tree with ID= MainTree.
Now, at run time I create an updated XML and call registerBehaviorTreeFromText with the same ID = MainTree.
But, when I call createTree("MainTree") it again gives me the previously regsitered tree, as per my understanding tree id and their xml are being stored in a map(tree_roots). If I am correct then the xml should have been updated and be present with same ID as c++ map would replace the value if key exists. What do you think is an issue?

**Comment by facontidavide** [comment]
Hi,

I don't support 3.8, unless it is a critical bug.

If this is important for you, I suggest submitting a PR with a failing unit test and I will take a look at it.
