### ISSUE TITLE
Windows Cmake Action not running tests

### ISSUE THREAD

**Issue by tony-p** [BehaviorTree/BehaviorTree.CPP#646]
The unit tests are currently not run by the cmake windows build action

```
Run ctest -C $BUILD_TYPE
  ctest -C $BUILD_TYPE
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    BUILD_TYPE: Release
Test project D:/a/BehaviorTree.CPP/BehaviorTree.CPP/build
No tests were found!!!
```

**Comment by tony-p** [comment]
Added this PR https://github.com/BehaviorTree/BehaviorTree.CPP/pull/647

Currently there is 1 test failing ` [  FAILED  ] Parallel.PauseWithRetry`

**Comment by facontidavide** [comment]
Thanks for reporting, I will have a look
