### ISSUE TITLE
Groot2 monitoring not working with ROS example

### ISSUE THREAD

**Issue by MithunKinarullathil** [BehaviorTree/BehaviorTree.CPP#648]
Hi, does anyone know how to connect groot2 monitoring tool when launching the ROS example [here](https://github.com/BehaviorTree/BehaviorTree.ROS/tree/master/launch)? Currently, it's timing out. Thank you. 

![image](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/51120171/d7205a32-0623-449f-a3e6-cc61a098c770)

**Comment by facontidavide** [comment]
To connect Groot2, you need to follow this tutorial.
 https://www.behaviortree.dev/docs/tutorial-basics/tutorial_12_groot2
 
 The example you mention doesn't have the **Groot2Publisher**
