### ISSUE TITLE
Tutorial 04 Reactive Behaviours - Expected Output is Incorrect

### ISSUE THREAD

**Issue by jmount-boss** [BehaviorTree/BehaviorTree.CPP#654]
In [Tutorial 04 Reactive Behaviours](https://www.behaviortree.dev/docs/tutorial-basics/tutorial_04_sequence) the output for the two trees differs from what is described in the tutorial. The produced output is are shown below. This output was produced using the [t04_reactive_sequence.cpp](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t04_reactive_sequence.cpp).

Sequence Tree
```
--- ticking
[ Battery: OK ]
Robot says: mission started...
[ MoveBase: SEND REQUEST ]. goal: x=1.0 y=2.0 theta=3.0
--- status: RUNNING

--- ticking
--- status: RUNNING

--- ticking
[ MoveBase: FINISHED ]
Robot says: mission completed!
--- status: SUCCESS
```

Reactive Tree
```
--- ticking
[ Battery: OK ]
Robot says: mission started...
[ MoveBase: SEND REQUEST ]. goal: x=1.0 y=2.0 theta=3.0
--- status: RUNNING

--- ticking
[ Battery: OK ]
--- status: RUNNING

--- ticking
[ Battery: OK ]
[ MoveBase: FINISHED ]
Robot says: mission completed!
--- status: SUCCESS
```

**Comment by facontidavide** [comment]
fixed
