### ISSUE TITLE
How to use groot to view the behavior trees of multiple threads

### ISSUE THREAD

**Issue by chakloong883** [BehaviorTree/BehaviorTree.CPP#662]
I want to use groot to monitor the behavior trees of two threads. When I use BT::PublisherZMQ, I find that I can only monitor a single instance. Is there a solution if I want to monitor two behavior trees at the same time?

**Comment by facontidavide** [comment]
not possible at the moment
Groot can only see a single tree executor at a time.

Even if I remove the single instance limitation, these publishers should be independent and use different IP ports
