### ISSUE TITLE
Feature Request: custom function definition plugins for scripts

### ISSUE THREAD

**Issue by mnumanuyar** [BehaviorTree/BehaviorTree.CPP#665]
is it possible to define custom function that we can use in scripting?

for example if i add a function "add(x,y){return x+y}" in cpp, i would use it as
```
<Script code="answer:=add(1,2)" />
```

**Comment by mnumanuyar** [comment]
If anyone can say it is possible and put some links, i am willing to spend some time on it

**Comment by facontidavide** [comment]
not possible. This feature will not be added anitime soon, sorry
