### ISSUE TITLE
`ReactiveSequence` not breaking upon first `RUNNING`

### ISSUE THREAD

**Issue by rlrosa** [BehaviorTree/BehaviorTree.CPP#674]
Hi, according to the documentation here:
  https://www.behaviortree.dev/docs/nodes-library/sequencenode/
in a `ReactiveSequence` if a child returns `RUNNING` the sequence should restart, so:

> "Restart" means that the entire sequence is restarted from the first child of the list.

if in my BT i have several nodes with an `on_running` function that just does:
```
return RUNNING;
```
should just the first be executed, and the rest halted?

shouldn't the source here:
  https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/src/controls/reactive_sequence.cpp#L56
be breaking out of the `while` loop after the first instance of `RUNNING` in order to achieve that?

If i understood this incorrectly then maybe the doc can be improved to make it less confusing.

Thanks.

**Comment by facontidavide** [comment]
ReactiveSequence does NOT work if multiple children have a RUNNING state.
I explicitly check that.

Please show a concrete example (or unit test) where the ReactiveSequence is acting differently than you expect.

Once you have that, I will be happy to reopen the issue. Documentation can be surely improved!!!
