### ISSUE TITLE
TinyXML symbols exported on VC++

### ISSUE THREAD

**Issue by Masadow** [BehaviorTree/BehaviorTree.CPP#68]
When compiling under msvc, tiny xml symbols are exported which is conflicting for me because I'm already using tinyxml on my own.

**Comment by facontidavide** [comment]
tell me if the last commit helps... even if I doubt it :(

I don't have much time to address this right bow, but I will eventually.

**Comment by Masadow** [comment]
It's not compiling at all now, complaining about BEHAVIOR_TREE_LIBRARY requiring BEHAVIOR_TREE_LIBRARY_EXTRA that is not exported. I don't know much about cmake nor windows compilation but since it's a must for my project at this point, I'll try to look at it and hopefully fix it as quickly as possible.

**Comment by facontidavide** [comment]
ok, that was not a good idea, I reverted the change....

**Comment by facontidavide** [comment]
I believe that I might have solve the issue with commit 108cd60c8c9716a639bb686d1d4e498fb9dc3225

Check it out

**Comment by Masadow** [comment]
It's fixed, good job !
