### ISSUE TITLE
possible typo in groot2 publisher code

### ISSUE THREAD

**Issue by mnumanuyar** [BehaviorTree/BehaviorTree.CPP#685]
I am trying to get familiresed with groot2 publisher code and noticed the line 
```
publisher.set(zmq::sockopt::rcvtimeo, timeout_rcv);
```
appears twice (in line 64 and line 68) here: 
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/a28df0f77ddcea7915693f276b27147b75d2c07f/src/loggers/groot2_publisher.cpp#L57-L69

is this a typo or intentional?

**Comment by facontidavide** [comment]
thanks!!! fixed
