### ISSUE TITLE
Ports with generic types: std::vector<Eigen::VectorXd>

### ISSUE THREAD

**Issue by yigezz** [BehaviorTree/BehaviorTree.CPP#689]
Try to parse my customized type, I tried `std::vector<Eigen::Isometry3d>`, it works as expected. But once I'm implementing a similar parser for `std::vector<Eigen::VectorXd>`. then I got the error: 
**_You (maybe indirectly) called BT::convertFromString() for type [std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >], but I can't find the template specialization._**
Tried to use the type `std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>` shows in error instead of  `std::vector<Eigen::VectorXd>`, but still got the same error.

**Comment by facontidavide** [comment]
please provide an example that reproduce the problem.

In general, this error happens when your implementation of `convertFromString` is not visible (not included) in the compilation unit where the registration of your node with the custom type happens.
