### ISSUE TITLE
[v4.x] Why does ControlNode::halt() DecoratorNode::halt() not set status to IDLE?

### ISSUE THREAD

**Issue by asasine** [BehaviorTree/BehaviorTree.CPP#694]
In cc7717108276bc687c57a9b63cb1a4a7b1f94b8f, the behavior was changed in `ControlNode::halt()` and `DecoratorNode::halt()` to no longer set the node's status to `IDLE` via a call to `resetStatus()` or `setStatus(NodeStatus::IDLE)`. However, it still resets the child's status.

It broke a couple of our custom controls and decorators, which called the base type `halt()` and relied on this behavior of the next `status()` after `halt()` returning `IDLE`. We can either fix it by calling `resetStatus()` in our own overridden `halt()`, or measuring whether we halted in other ways. Before putting either of those patches in, I wanted to check what the motivations were for removing the call from the base type `halt()` implementations.

My best guess is that it makes the contract more explicit that the parent node should reset the status of the child when halted. Is that correct?

**Comment by facontidavide** [comment]
this was a deliberate decision that I should probably revert.
I will let you know when I apply the fix
