### ISSUE TITLE
Real-time Visualization in Groot: is it included in the Basic package?

### ISSUE THREAD

**Issue by sgarciav** [BehaviorTree/BehaviorTree.CPP#711]
Hello: It's not clear to me if the ability to monitor my nodes with Groot2 in real-time is part of the Basic package.

In the main [behaviortree.dev](https://www.behaviortree.dev/groot/) website, under the "Pricing" section, the Basic package states:
"Monitor and Log Visualizer limited to 20 Nodes"

However, in the [tutorial docs](https://www.behaviortree.dev/docs/tutorial-basics/tutorial_12_groot2/#adding-real-time-visualization-to-groot), there is a note that states:
"Currently, only the PRO version of Groot2 supports real-time visualization."

I am a user of the Basic package for Groot2. I have tried adding the line `BT::Groot2Publisher publisher(tree);` to my executor node, but it doesn't compile. So my questions are:

- Is the ability to monitor my nodes in real-time available for the Basic package?
- If yes, are there any other steps I need to take other than adding the `Groot2Publisher` line to my executor node?

Any information is more than welcomed. Thanks!

**Comment by facontidavide** [comment]
It should work.can you tell me more about your error?

**Comment by facontidavide** [comment]
I don't understand, everything looks ok.

If you use the same code from tutorial 12, does it work?

**Comment by facontidavide** [comment]
Are you sure that `publisher` and `tree_` don't go out of scope? 
I am 90% positive that you are calling this inside a method and that `publisher` is destroyed immediately.

If that is the case, you may want to define an attribute in your class like

```cpp
std::unique_ptr<BT::Groot2Publisher> publisher_;
```

and change your code to:

```cpp
tree_ = factory_.createTreeFromFile(tree_file_path);
const unsigned port = 1667;
publisher_ = std::make_unique<BT::Groot2Publisher >(tree_, port);
```

**Comment by sgarciav** [comment]
This was exactly the problem. I tested it out and everything is working as expected. Thanks for the reply!

**Comment by facontidavide** [comment]
![image](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/2822888/b8f8e7a3-b962-400c-96cd-811c1c0e0761)
