### ISSUE TITLE
Catkin make problem

### ISSUE THREAD

**Issue by ariccspstk** [BehaviorTree/BehaviorTree.CPP#712]
I am trying to install the packages into my ubuntu melodic and i am having difficulties can someone help !

In file included from /home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:31:0,
                 from /home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/basic_types.h:16,
                 from /home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/tree_node.h:22,
                 from /home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/leaf_node.h:17,
                 from /home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/action_node.h:22,
                 from /home/ubuntu/behaviour/src/BehaviorTree.CPP/src/action_node.cpp:16:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp: In instantiation of ‘void SafeAny::details::convertNumber(const SRC&, DST&) [with SRC = long int; DST = long int]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:416:32:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::convert(BT::Any::EnableArithmetic<DST>) const [with DST = long int; BT::Any::EnableArithmetic<DST> = void*; typename std::enable_if<std::is_arithmetic<_Tp>::value>::type = void]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:479:27:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::tryCast() const [with T = long int]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:158:29:   required from ‘T BT::Any::cast() const [with T = long int]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:301:32:   required from here
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp:107:20: warning: variable ‘both_integers’ set but not used [-Wunused-but-set-variable]
     constexpr bool both_integers = is_integer<SRC>() && is_integer<DST>();
                    ^~~~~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp: In instantiation of ‘void SafeAny::details::convertNumber(const SRC&, DST&) [with SRC = long unsigned int; DST = long unsigned int]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:420:33:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::convert(BT::Any::EnableArithmetic<DST>) const [with DST = long unsigned int; BT::Any::EnableArithmetic<DST> = void*; typename std::enable_if<std::is_arithmetic<_Tp>::value>::type = void]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:479:27:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::tryCast() const [with T = long unsigned int]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:158:29:   required from ‘T BT::Any::cast() const [with T = long unsigned int]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:305:33:   required from here
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp:107:20: warning: variable ‘both_integers’ set but not used [-Wunused-but-set-variable]
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp: In instantiation of ‘void SafeAny::details::convertNumber(const SRC&, DST&) [with SRC = double; DST = double]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:424:31:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::convert(BT::Any::EnableArithmetic<DST>) const [with DST = double; BT::Any::EnableArithmetic<DST> = void*; typename std::enable_if<std::is_arithmetic<_Tp>::value>::type = void]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:479:27:   required from ‘nonstd::expected_lite::expected<T, std::__cxx11::basic_string<char> > BT::Any::tryCast() const [with T = double]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:158:29:   required from ‘T BT::Any::cast() const [with T = double]’
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/safe_any.hpp:309:31:   required from here
/home/ubuntu/behaviour/src/BehaviorTree.CPP/include/behaviortree_cpp/utils/convert_impl.hpp:107:20: warning: variable ‘both_integers’ set but not used [-Wunused-but-set-variable]
[  3%] Building CXX object CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:119:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:119:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = long int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:131:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:131:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = unsigned int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:143:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:143:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = long unsigned int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:155:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:155:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
CMakeFiles/behaviortree_cpp.dir/build.make:89: recipe for target 'CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o' failed
make[2]: *** [CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/behaviortree_cpp.dir/all' failed
make[1]: *** [CMakeFiles/behaviortree_cpp.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
ubuntu@Gluon:~/behaviour/src/BehaviorTree.CPP/build$ sudo make install
[  2%] Built target lexy_file
[  3%] Building CXX object CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:119:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:119:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = long int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:131:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:131:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = unsigned int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:143:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:143:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp: In function ‘T BT::convertFromString(BT::StringView) [with T = long unsigned int; BT::StringView = std::basic_string_view<char>]’:
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:155:25: error: ‘from_chars’ is not a member of ‘std’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
/home/ubuntu/behaviour/src/BehaviorTree.CPP/src/basic_types.cpp:155:25: note: suggested alternative: ‘__is_char’
   auto [ptr, ec] = std::from_chars(str.data(), str.data() + str.size(), result);
                         ^~~~~~~~~~
                         __is_char
CMakeFiles/behaviortree_cpp.dir/build.make:89: recipe for target 'CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o' failed
make[2]: *** [CMakeFiles/behaviortree_cpp.dir/src/basic_types.cpp.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'CMakeFiles/behaviortree_cpp.dir/all' failed
make[1]: *** [CMakeFiles/behaviortree_cpp.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by facontidavide** [comment]
Ubuntu Melodic and Ubuntu 18.04 are not supported anymore (end of life).

It is a problem with C++17 support.
