### ISSUE TITLE
Tree::getNodesByPath returns a list of constant pointers but the method is not marked constant

### ISSUE THREAD

**Issue by Jazzinghen** [BehaviorTree/BehaviorTree.CPP#713]
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/ae95e680ab3c58f1e773f05d6372c10f41b546e8/include/behaviortree_cpp/bt_factory.h#L165

I wanted to traverse some nodes in a function where I get a constant reference to a tree but I cannot call this function as it is not marked as constant even though it doesn't modify the object data.

**Comment by facontidavide** [comment]
fixed
