### ISSUE TITLE
Implementing a version getNodesByPath() returning non const results

### ISSUE THREAD

**Issue by Lecrapouille** [BehaviorTree/BehaviorTree.CPP#717]
Hello, 

is there any particular reason the `std::vector<const TreeNode*> getNodesByPath(StringView wildcard_filter)`  returns a container of const nodes ? Adding non const version `std::vector<TreeNode*> getNodesByPath(StringView wildcard_filter)` in your API would be nice.

Indeed, after calling `factory.createTreeFromFile` I would like to call some methods from these nodes to end the initialization phase. I know I can use `tree.applyVisitor`, as explained in the documentation, but in my case, the derived classes from BT::Node shall know each of them and the visitor is not the best option. The blackbox is not a good option.

Here what I'm trying to reach in pseudo C++:

```
auto A = dynamic_cast<A*>(tree.findNode("a"));
auto B = dynamic_cast<B*>(tree.findNode("b"));
auto C = dynamic_cast<C*>(tree.findNode("c"));
A->foobar(B, C); // Note: this is to end the init phase not for calling at each tick()
```

EDIT:
- a good point is that I could be able to redo this non-const helper function outside BT.cpp code source.
- may be the result `std::vector<const TreeNode*>` should be `std::vector<const NodeType*>` to avoid having to do a second dynamic_cast (slow) when iterating on nodes (same idea for non const).

Here is my suggestion (not tested):
``` 
  template <typename NodeType = BT::TreeNode> [[nodiscard]]
  std::vector<NodeType*> getNodesByPathV2(BT::StringView wildcard_filter) {
    std::vector<NodeType*> nodes;
    for (auto& subtree : subtrees) {
      for (auto& node : subtree->nodes) {
        if(auto node_recast = dynamic_cast<NodeType*>(node.get())) {
          if (BT::WildcardMatch(node->fullPath(), wildcard_filter)) {
            nodes.push_back(node_recast);
          }
        }
      }
    }
    return nodes;
  }
```

Edit: I'm even wondering if not better to use `std::dynamic_pointer_cast` to return container of shared_pointer cast to the desired subclass.

**Comment by facontidavide** [comment]
Your suggested code looks good to me and you can use `dynamic_pointer_cast`, as you said.
I don't think that there is any action needed from my side, so I am closing the issue
