### ISSUE TITLE
Groot: In case of custom type variables groot prints null in line with the variable name

### ISSUE THREAD

**Issue by AnkitSaini** [BehaviorTree/BehaviorTree.CPP#722]
As shown in the attached picture. The custom type variable has a value. But "null" is printed in the line of the variable name. The "null" remains even when the value is constantly getting updated. 

![Screenshot from 2023-12-14 10-47-51](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/6428004/b14770d6-ad1a-4775-a337-eeaabd1f98d1)

**Comment by facontidavide** [comment]
thanks for reporting!

**Comment by facontidavide** [comment]
fixed in the new version of groot (to be released soon)
