### ISSUE TITLE
Post script executes even when the node is skipped 

### ISSUE THREAD

**Issue by ufrhaidar** [BehaviorTree/BehaviorTree.CPP#757]
the **_post** Post Condition gets executed even when the node is skipped due to a Pre Condition.

From the documentation:
| Name | Description |
|-------------|---------|
| **_post**      | Execute this script, if the Node returned either SUCCESS or FAILURE |

I think it either needs to be fixed, or the documentation should say that the script would also execute when the node returns SKIPPED.

**Comment by facontidavide** [comment]
this seems like a serious bug that I should address immediately.

Do you have a simple example / unit tests to reproduce the issue?

**Comment by ufrhaidar** [comment]
![Screenshot from 2024-02-01 08-35-30](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/110574820/de3539e3-6b98-4aa1-aa33-3ba424d5893a)

This simple tree can reproduce the error.
It was printing good then bad

```
[behavior_tree_engine_node-1] [INFO] [1706740514.701689945] [behavior_tree_engine]: [UFR2_PrintString] Value: good
[behavior_tree_engine_node-1] [INFO] [1706740514.701755465] [behavior_tree_engine]: [UFR2_PrintString] Value: bad
```

**Comment by ufrhaidar** [comment]
Found issue:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/d4d6514966d416996efc624e567a45c0cc0bdeab/src/tree_node.cpp#L255

can be also fixed by checking if it is skipped before running this:

https://github.com/BehaviorTree/BehaviorTree.CPP/blob/d4d6514966d416996efc624e567a45c0cc0bdeab/src/tree_node.cpp#L112
