### ISSUE TITLE
Allow concatenation of string and numbers in scripting

### ISSUE THREAD

**Issue by bochen87** [BehaviorTree/BehaviorTree.CPP#766]
Currently, only concatenation of strings is allowed. Trying to concatenate a number and a  string leads to a runtime error https://github.com/BehaviorTree/BehaviorTree.CPP/blob/58326a8a08d9c51e2ed8674aef3710bb6209867b/include/behaviortree_cpp/scripting/operators.hpp#L255

It would be nice to also allow concatenation of string and numbers

**Comment by facontidavide** [comment]
I can see the use case, I will put this on my list of "todo".

**Comment by bochen87** [comment]
> I can see the use case, I will put this on my list of "todo".

I made a PR https://github.com/BehaviorTree/BehaviorTree.CPP/pull/771
