### ISSUE TITLE
ROS specific tutorial/example

### ISSUE THREAD

**Issue by doisyg** [BehaviorTree/BehaviorTree.CPP#77]
Hello,
Not sure it is the right place to ask, but is there any example of BehaviorTree.CPP interacting with ROS (1) somewhere? And even better a sample calling a ROS action?
I am looking for good practice sample to start using it.

**Comment by facontidavide** [comment]
my fault, I should have done this earlier. My plan is to add such examples here.... https://github.com/BehaviorTree/BehaviorTree.ROS

**Comment by doisyg** [comment]
Looking forward to it!
(in the meantime, any public repo using BehaviorTree.CPP with ROS, even not documented, will help)

**Comment by bhagwanalbert** [comment]
Hello,
Your library has been recommended to us and our goal it to implement it with ROS nodes, so I am also interested in a basic example of how to combine these two. May I know approximately when we will be able to have one basic tutorial?
Thanks in advance,
Albert.

**Comment by facontidavide** [comment]
This is the basic example you are looking for:

https://github.com/BehaviorTree/BehaviorTree.ROS/tree/master/src/actions

Cheers

**Comment by varunvp** [comment]
> This is the basic example you are looking for:
> 
> https://github.com/BehaviorTree/BehaviorTree.ROS/tree/master/src/actions
> 
> Cheers

This package, after catkin building, doesn't generate any executable, so nothing in it can be rosrun. What changes should I make to the CMakeLists.txt? Your package is a library, but any executable referring to it throws an error saying that there is no main.
