### ISSUE TITLE
Blackboard -> Clear() kills the tree execution ? 

### ISSUE THREAD

**Issue by viprob-ai** [BehaviorTree/BehaviorTree.CPP#794]
After one full tree execution on clearing blackboard ( **blackboard->clear()** ) [need to clear for my case] on ticking the tree again for next execution kill the process.

Not sure what the reason.

What is the correct way to clear the blackboard **after each** full tree execution ?

**Comment by facontidavide** [comment]
Yes, clear was a bad idea. Please check this example instead: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/ex07_blackboard_backup.cpp
