### ISSUE TITLE
CMake Error when using "target_link_libraries(myBehaviorTree BT::behaviortree_cpp)

### ISSUE THREAD

**Issue by gcMs1** [BehaviorTree/BehaviorTree.CPP#801]
Hi, 
I am facing difficulties compiling my CMake project on ubuntu22.04. The following are the content of my CMakelists.txt and the errors in details. By the way, I have installed Behavior_CPP in my computer. Could you kindly help me?

CMakelists.txt:
```
cmake_minimum_required(VERSION 3.5)

project(btcpp_sample LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(btcpp_sample main.cpp)

find_package(behaviortree_cpp REQUIRED)
target_link_libraries(btcpp_sample BT::behaviortree_cpp)
```

ERRORS:
![截图 2024-04-04 22-17-30](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/100077449/50c27db4-3efd-4f29-8b1f-5d848e24dc07)

**Comment by facontidavide** [comment]
should be fixed with a recent PR merged
