### ISSUE TITLE
setPreTickOverrideFunction not implemented in 3.8.6

### ISSUE THREAD

**Issue by mlampel** [BehaviorTree/BehaviorTree.CPP#807]
Hi, 
In the TreeNode class, the setPreTickOverrideFunction method is declared in the header file, but its implementation is missing in the tree_node.cpp file:
 https://github.com/BehaviorTree/BehaviorTree.CPP/blob/ae5b949b6570bc6fa94f0b464742ed8d670fbcd1/include/behaviortree_cpp_v3/tree_node.h#L123

The functionality for this pretick method is implemented in the executeTick. Is it possible to fix this?

**Comment by facontidavide** [comment]
Yes, that was a placeholder.

This will never be supported on 3.X branch
