### ISSUE TITLE
Impossible to write to global blackboard using output ports

### ISSUE THREAD

**Issue by robin-mueller** [BehaviorTree/BehaviorTree.CPP#823]
In my application I am trying to write to a global blackboard entry using `setOutput` of a tree node, but an entry in the local blackboard is created instead.

Let an example be:

```xml
<BehaviorTree ID="MainTree">
    <Sequence>
        <Script code="@global_var:=0"/>
        <SubTree ID="BugExample" />
    </Sequence>
</BehaviorTree>

<BehaviorTree ID="BugExample">
    <Sequence>
        <SetState in="1"/>
        <GetState out="{@global_var}"/>
    </Sequence>
</BehaviorTree>
```

The nodes `SetState` and `GetState` set respectively get the value of an internal state variable using the corresponding ports. With the latest version to date, `global_var` is created in the blackboard of *MainTree* with value 0 and `@global_var` in the blackboard of *BugExample* with value 1. The expected behavior would be that `GetState` updates the entry `global_var` in *MainTree* as I understand it.

I'd suggest to implement an example like this in the associated [test](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/287eb59cefdc375cfd45bfa1431a840163e8199a/tests/gtest_blackboard.cpp#L566-L608) to verify this issue, since I don't see that it is covered yet.

**Comment by robin-mueller** [comment]
I've added the test in the pull request above.

I currently don't have too much time to look into it, but I assume the issue to have its origin [here](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/287eb59cefdc375cfd45bfa1431a840163e8199a/include/behaviortree_cpp/blackboard.h#L203). `storage_` is searched for a key `@global_var` which obviously cannot be found.

**Comment by facontidavide** [comment]
fixed
