### ISSUE TITLE
Conflict between Node and SubTree names

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/BehaviorTree.CPP#827]
**Describe the bug**

If there is a node and a SubTree with same name, and the SubTree has some ports defined using `TreeNodesModel`, when trying to call the subtree it would throw the following error:
```
a port with name [param1] is found in the XML, but not in the providedPorts()
```

The error goes away if I rename the SubTree. I understand that having a same name is not recommended, but I just wanted to let you know that this bug appeared recently, it was not the case before.

**Comment by facontidavide** [comment]
You must not have a node and Subtree with the same name. The real "bug" is allowing it must be prevented
