### ISSUE TITLE
How to start failed(or interruptted) tree from remained actions?

### ISSUE THREAD

**Issue by robologics1** [BehaviorTree/BehaviorTree.CPP#835]
For example my robot powered off while roaming ,and I need to tick remained action first. How can I start behavior tree from last status? How can I initialize behavior tree according to bt status? Any help appreciated. Thank you.

**Comment by facontidavide** [comment]
Have a look to this. https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t17_blackboard_backup.cpp

It might help a little, but probably it is MUCH more complicated than that.
