### ISSUE TITLE
There is a bug in tutorial_01_first_tree

### ISSUE THREAD

**Issue by oliveryoung** [BehaviorTree/BehaviorTree.CPP#84]
run "t01_first_tree_dynamic" program will prompt: could not load library : ./libdummy_nodes.so: cannot open shared object file: no such file or directory.
Line 73 in the  program:
-factory.registerFromPlugin("./libdummy_nodes.so");
+factory.registerFromPlugin("../libdummy_nodes_dyn.so");

**Comment by facontidavide** [comment]
Fixed. thanks for reporting
