### ISSUE TITLE
Unable to use nodes as plugins in behavior tree v4.5

### ISSUE THREAD

**Issue by nilutpol-k** [BehaviorTree/BehaviorTree.CPP#842]
Hi, 
I am trying to use behavior tree nodes as plugins in ROS 2 code. 

My tree has just 1 node 
```
<?xml version="1.0"?>
<root BTCPP_format="4" >
    <BehaviorTree ID="BehaviorTree">
        <ReactiveSequence>
	    <Action ID="Node1"/>
        </ReactiveSequence>
    </BehaviorTree>
    <TreeNodesModel>
        <Action ID="Node1"/>
    </TreeNodesModel>
</root>
```
Here is the code I added to my CMakelists.txt to use the nodes as plugins 
```
add_library(bt_plugin1 SHARED src/behavior_tree_plugins/Node1.cpp)

list(APPEND plugin_libs
  bt_plugin1
)

foreach(bt_plugin ${plugin_libs})
  ament_target_dependencies(${bt_plugin} ${dependencies})
  target_compile_definitions(${bt_plugin} PRIVATE BT_PLUGIN_EXPORT)
endforeach()

...
...

install(TARGETS
  ${plugin_libs}
  bt_plugins_main
  DESTINATION lib/${PROJECT_NAME})
```

**My ROS 2 package structure**
```
behavior_tree_plugins/
├── package.xml
├── CMakeLists.txt
├── src/
      ├── behavior_tree_plugins/
              └── Node1.cpp
      └── bt_plugins_main.cpp
└── xml/
      └── tree1.xml
```

**My main behavior tree code for loading the plugins** (partial code)
```
    ....
    BT::SharedLibrary loader;

    factory.registerFromPlugin(loader.getOSName("bt_plugin1"));
    ....
```

**The error**

My code compiles successfully but my main behavior tree code is not able to load the Node1 library successfully as it is not able to find it. 

I get the error as 
```
terminate called after throwing an instance of 'BT::RuntimeError'
  what():  Could not load library: libbt_plugin1.so: cannot open shared object file: No such file or directory

```

![Screenshot from 2024-07-01 12-15-11](https://github.com/BehaviorTree/BehaviorTree.CPP/assets/144599925/68ae5ce0-3ce7-49f5-b7f0-79c3c73f9d90)

**System Details:**
OS: Ubuntu 22.04
ROS 2: Humble 
Behavior tree version: 4.5

**Comment by facontidavide** [comment]
The path where the file is will not be found magically. You need to specify the actual path.
This may help: https://index.ros.org/p/ament_index_cpp/

**Comment by nilutpol-k** [comment]
Hi @facontidavide 

> specify the actual path

where do I mention the actual file paths?
