### ISSUE TITLE
Question about setPreTickFunction

### ISSUE THREAD

**Issue by robologics1** [BehaviorTree/BehaviorTree.CPP#859]
I am trying to add constant check function to my structure via setPreTickFunction() . I want the node whose turn it is to check the condition just before it runs. Should I write the following code inside a while loop, or is it enough to set the pretickfunction just once?
Additionally, in the code below, it prints the ros_info and the second cerr message, but it does not print the cerr message inside the lambda function, so I think I am making a mistake somewhere in the pretickfunction. Thank you.
Function
`void Test::setupActionNodesPreTick(BT::Tree& tree_)
{
  tree_.applyVisitor([&](BT::TreeNode* node) -> void {
    
        if (node->type() == BT::NodeType::ACTION && node->config().action_ptr->conditions != "null") 
        {
          
            ROS_INFO("it arrives here %s ", node->config().action_ptr->conditions.c_str());
            
            node->setPreTickFunction([this, node](BT::TreeNode& action_node) -> BT::NodeStatus {
            std::cerr << "Processing node in : " << node->registrationName().c_str() << std::endl;
            if (!this->checkConditions(node->config().action_ptr->conditions)) {
            return BT::NodeStatus::SKIPPED;
            }
            return BT::NodeStatus::IDLE;
            });

            std::cerr << "Processing node in : " << node->registrationName().c_str() << std::endl;
          
        }
    });
  
}`

**Comment by b-adkins** [comment]
There are pre-conditions built into BT.CPP scripting language. This may interest you if you're using the blackboard: https://www.behaviortree.dev/docs/guides/pre_post_conditions

No, you don't need a while loop. Each invocation of setPreTickFunction overwrites the previous pre-tick callback, if there was one.

I don't think a preTickFunction will work properly if it returns IDLE or SKIPPED. If it returns RUNNING, the node ticks as usual; if it returns SUCCESS or FAILURE, the node will not tick.
