### ISSUE TITLE
little bug in 3rdparty/lexy

### ISSUE THREAD

**Issue by houhuawei23** [BehaviorTree/BehaviorTree.CPP#865]
**Describe the bug**
in 3rdparty/lexy/include/lexy/input_location.hpp line 165
```cpp
        return lhs._column_nr < rhs._colum_nr;
```
should be 
```cpp
        return lhs._column_nr < rhs._column_nr;
```
one 'n' is missing.

I'm a newbie in this project, but my first build error at this bug. It is very odd that no body else find this, maybe this srdparty lib is not used?

**Comment by facontidavide** [comment]
solved
