### ISSUE TITLE
Is there any library or tool available to visualize BehaviorTree.CPP XML files as images?

### ISSUE THREAD

**Issue by harderthan** [BehaviorTree/BehaviorTree.CPP#878]
Is there a library or tool that can visualize XML files as images? Can Groot support this?

I would like to set up a GitHub Bot that, when a commit containing changes to an XML file is made into a PR, automatically visualizes the XML file as an image and attaches it as a comment. Ideally, it would be great if the changes could be highlighted with different colors.

**Comment by SteveMacenski** [comment]
We have one in Nav2 in the tools directory. I won’t say the images are particularly good looking though, but they work for engineering use cases

**Comment by facontidavide** [comment]
Groot can't be used like that, so, from my side, the answer is "no"
