### ISSUE TITLE
Cannot use Blackboard key/value defined in a subTree

### ISSUE THREAD

**Issue by BriceRenaudeau** [BehaviorTree/BehaviorTree.CPP#89]
Hello,
I have a pretty long Init sequence that I would like to define as a subTree.
But when I do so, le blackboard entry cannot be used in the MainTree.

Is there a way to solve this problem?

**Comment by facontidavide** [comment]
I am going to ask a very silly question: have you read this?

https://www.behaviortree.dev/tutorial_06_subtree_ports/

**Comment by BriceRenaudeau** [comment]
Thank you, that's right I missed this part.
Sorry for the question.
