### ISSUE TITLE
Header file referenced that doesn't exist any longer

### ISSUE THREAD

**Issue by marc-hanheide** [BehaviorTree/BehaviorTree.CPP#891]
Just noticed that the file `BT_logger_generated.h` referenced in https://github.com/BehaviorTree/BehaviorTree.CPP/blob/f5e98fd751523fd2797e5353cb9f1cc765587cb4/include/behaviortree_cpp/flatbuffers/bt_flatbuffer_helper.h#L4

does not exist any longer, since commit https://github.com/BehaviorTree/BehaviorTree.CPP/commit/a1291695cbf0f28bf866577374089e93b570a56d. 

Came across this trying to make https://github.com/ipa-rwu/Groot compile.

**Comment by facontidavide** [comment]
The original Groot has been discontinued and it is NOT supposed to work with version 4.0 or later.
