### ISSUE TITLE
Limit of the tic frequency

### ISSUE THREAD

**Issue by BriceRenaudeau** [BehaviorTree/BehaviorTree.CPP#90]
Hello,
I would like to know if there is a parameter to limit the tic frequency or is it limited by the CPU?
Is there a good way to do it ?
Currently I am using "wait" nodes to delay the execution.

**Comment by facontidavide** [comment]
No, and that is by purpose. I usually add a wait in the main loop.

See here: https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t05_crossdoor.cpp#L90
